### ISSUE TITLE
[BUG] 查询历史战绩时, 不会自动展示第一局的详情(显示为空白页)

### ISSUE THREAD

**Issue by Hpero4** [Zzaphkiel/Seraphine#132]
![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/0d5ef253-1236-4b1d-8208-b491c983b1d1)

Seraphine Ver: v0.9.0-dev
发布版本是否存在该问题: 是

复现手顺:
1. 找一个很久没打游戏的玩家进生涯页
2. 通过生涯页点击某一局战绩
3. 右上角提示数据加载完成, 但页面未跳转到"战绩查询"; 届时若手动切换, 会发现搜索框有该召唤师名称, 但查不出任何一盘战绩
4. 查询一个一年内有对局记录的召唤师, 问题复现

预期行为:
1. 生涯页的历史战绩, 应与战绩查询页的可查询范围保持一致.
2. 在尝试加载一局查询不到对局详情后, 不应引发逻辑错误

问题导向:
1. 初步推测是因为战绩查询范围为一年, 但生涯页未作限制, 尝试加载超出近一年的战绩时, 查询的线程会直接退出不予加载, 导致看不到详情.
2. 历史战绩的对局详情部分参数传递存在问题, 大致定位在发送了详情页准备信号但未实际传入详情页数据; 后续再次调用时, 目标召唤师已经更改, 导致此前puuid无法在当前实际的详情页数据中匹配到玩家, 数据解析失败.

异常发生时, log有输出:
```
Exception in thread Thread-106:
Traceback (most recent call last):
  File "C:\Users\Jiangh\.conda\envs\seraphine\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Jiangh\.conda\envs\seraphine\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "K:\Code\Seraphine\app\view\search_interface.py", line 117, in _
    game = processGameDetailData(self.puuid, game)
  File "K:\Code\Seraphine\app\lol\tools.py", line 346, in processGameDetailData
    mapIcon = connector.manager.getMapIconByMapId(mapId, win)
UnboundLocalError: local variable 'win' referenced before assignment
```

**Comment by Zzaphkiel** [comment]
已修复该问题
