### ISSUE TITLE
[BUG] 对局信息加载不出来

### ISSUE THREAD

**Issue by jerry333333** [Zzaphkiel/Seraphine#205]
### 问题描述

无法查看对局信息  
2024-01-13 05:01:46,040 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "urllib3\connection.py", line 203, in _new_conn
  File "urllib3\util\connection.py", line 85, in create_connection
  File "urllib3\util\connection.py", line 73, in create_connection
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1096, in _validate_conn
  File "urllib3\connection.py", line 611, in connect
  File "urllib3\connection.py", line 218, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000282E33443D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=1539): Max retries exceeded with url: /lol-match-history/v1/products/lol/21e59002-09c9-503f-98a4-742a9387dab5/matches?begIndex=0&endIndex=14 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000282E33443D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\lol\connector.py", line 73, in wrapper
  File "app\lol\connector.py", line 382, in getSummonerGamesByPuuid
  File "app\lol\connector.py", line 113, in wrapper
  File "app\lol\connector.py", line 618, in __get
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=1539): Max retries exceeded with url: /lol-match-history/v1/products/lol/21e59002-09c9-503f-98a4-742a9387dab5/matches?begIndex=0&endIndex=14 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000282E33443D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

2024-01-13 05:01:46,043 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "urllib3\connection.py", line 203, in _new_conn
  File "urllib3\util\connection.py", line 85, in create_connection
  File "urllib3\util\connection.py", line 73, in create_connection
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1096, in _validate_conn
  File "urllib3\connection.py", line 611, in connect
  File "urllib3\connection.py", line 218, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000028D8937BF10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=1539): Max retries exceeded with url: /lol-match-history/v1/products/lol/4010e67b-e2ac-58d4-a1b3-93a0ef94122a/matches?begIndex=0&endIndex=14 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028D8937BF10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\lol\connector.py", line 73, in wrapper
  File "app\lol\connector.py", line 382, in getSummonerGamesByPuuid
  File "app\lol\connector.py", line 113, in wrapper
  File "app\lol\connector.py", line 618, in __get
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=1539): Max retries exceeded with url: /lol-match-history/v1/products/lol/4010e67b-e2ac-58d4-a1b3-93a0ef94122a/matches?begIndex=0&endIndex=14 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028D8937BF10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.10.1

### 您进行游戏的服务器（若有）

皮城警备

### 出现率（若有）

未进行具体的重复测试

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by jerry333333** [comment]
系统是win10

**Comment by lengyingmofeng** [comment]
可能是你开了代理吧

**Comment by Zzaphkiel** [comment]
感谢您的反馈，同 #205，应该是服务器的问题。
