### ISSUE TITLE
[Question] （时不时会弹出这个提示）

### ISSUE THREAD

**Issue by neverfox9** [Zzaphkiel/Seraphine#210]
### 问题描述

Traceback (most recent call last):
  File "app\view\main_window.py", line 925, in __onGoingSwap
KeyError: 'summoners'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\view\main_window.py", line 936, in __onGoingSwap
UnboundLocalError: local variable 'tmp' referenced before assignment

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈，希望您可以提供一下游戏大区日志文件以及复现过程。

（另：与 #204 重复了，请移步 #204 进行讨论）
