### ISSUE TITLE
[BUG] 新版打不开捏，如图所示

### ISSUE THREAD

**Issue by xiaolu88** [Zzaphkiel/Seraphine#227]
### 问题描述

Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "app\common\qfluentwidgets.py", line 4, in <module>
ModuleNotFoundError: No module named 'qfluentwidgets'

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

10.0.2

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，是仓库中 `requirements.txt` 中的错误导致该问题，目前已经修复了。

您可以点击 [这里](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.10.2) 重新下载一下，应该可以使用了~
