### ISSUE TITLE
[Question] 运行报错

### ISSUE THREAD

**Issue by Ninohana** [Zzaphkiel/Seraphine#240]
## 运行环境

win11 x64 conda

python main.py

## 问题描述

云顶双人模式组队时候运行，直接报错

## 日志

```bash
Traceback (most recent call last):
  File "C:\Users\ninoh\Project\Seraphine\app\view\game_info_interface.py", line 93, in __onAllySummonerInfoReady
    self.summonersView.allySummoners.updateSummoners(info['summoners'])  # 概览栏(左侧)
  File "C:\Users\ninoh\Project\Seraphine\app\view\game_info_interface.py", line 244, in updateSummoners
    summonerView = SummonerInfoView(summoner, self)
  File "C:\Users\ninoh\Project\Seraphine\app\view\game_info_interface.py", line 287, in __init__
    self.__setColor(info["teamId"])
  File "C:\Users\ninoh\Project\Seraphine\app\view\game_info_interface.py", line 445, in __setColor
    assert 0 < len(self.parent().teamIdBuf) < 3  # 预组队数量一定不超过2
AssertionError
```

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈，经排查发现是由于在进行 **云顶之弈双人组队模式** 时，对局信息界面依旧尝试进行加载导致的。

目前 [`25dfb41`](https://github.com/Zzaphkiel/Seraphine/commit/25dfb417253657bb5b2a303f8e3aeed3ff94d08a) 已修复该问题。
