### ISSUE TITLE
[BUG] 启动即报异常

### ISSUE THREAD

**Issue by mzji** [Zzaphkiel/Seraphine#266]
### 问题描述

运行 `Seraphine.exe` 就报错
异常信息：
```
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 452, in __onLolClientStarted
  File "app\view\auxiliary_interface.py", line 956, in updateCompleter
  File "app\view\auxiliary_interface.py", line 972, in validate
AttributeError: 'AutoSelectChampionCard' object has no attribute 'switchButton'
```

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

master （github actions build）

### 客户端状态（若有）

主页闲置

### 复现方法（若有）

直接双击运行就报错， 100% 可复现

### 日志文件

`Seraphine_2024-03-05_ERROR.log`:
```
2024-03-05 20:08:26,610 - [MainWindow] CRITICAL - Seraphine started, version: 0.10.3
2024-03-05 20:08:31,082 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-03-05 20:08:31,083 - [MainWindow] CRITICAL - Seraphine listerners started
2024-03-05 20:08:31,323 - [MainWindow] CRITICAL - Seraphine initialized
2024-03-05 20:08:32,136 - [MainWindow] CRITICAL - League of Legends client started, server: WT2_NEW
2024-03-05 21:18:31,232 - [MainWindow] CRITICAL - Seraphine started, version: 0.10.3
2024-03-05 21:18:34,088 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-03-05 21:18:34,088 - [MainWindow] CRITICAL - Seraphine listerners started
2024-03-05 21:18:34,428 - [MainWindow] CRITICAL - Seraphine initialized
2024-03-05 21:20:10,175 - [MainWindow] CRITICAL - Seraphine started, version: 0.10.3
2024-03-05 21:20:12,749 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-03-05 21:20:12,749 - [MainWindow] CRITICAL - Seraphine listerners started
2024-03-05 21:20:12,922 - [MainWindow] CRITICAL - Seraphine initialized
2024-03-05 21:23:19,890 - [MainWindow] CRITICAL - Seraphine started, version: 0.10.3
2024-03-05 21:23:21,731 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-03-05 21:23:21,732 - [MainWindow] CRITICAL - Seraphine listerners started
2024-03-05 21:23:21,871 - [MainWindow] CRITICAL - Seraphine initialized
```

### 您进行游戏的服务器（若有）

德玛西亚

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
变量名忘改了 😨，刚刚在 [`04d8565`](https://github.com/Zzaphkiel/Seraphine/commit/04d8565d676c51c535b2cfe202c476bd9246ef07) 修复了该问题，感谢！
