### ISSUE TITLE
[BUG] 打开游戏后打开软件经常闪退

### ISSUE THREAD

**Issue by ilixtic** [Zzaphkiel/Seraphine#272]
### 问题描述

经常打开软件后闪退，稳定性有问题

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.10.3

### 客户端状态（若有）

打开

### 复现方法（若有）

经常出现

### 日志文件

[Seraphine_2024-03-10_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14548999/Seraphine_2024-03-10_ERROR.log)
[Seraphine_2024-03-10_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14549009/Seraphine_2024-03-10_ERROR.log)

### 您进行游戏的服务器（若有）

艾欧尼亚，台服

### 出现率（若有）

差不多一半的情况会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
请问是客户端还是 Seraphine 闪退😥？

**Comment by SSSctt** [comment]
有些玩家的信息不能查是为啥，提示Traceback (most recent call last):
  File "app\view\career_interface.py", line 364, in __onCareerInfoChanged
KeyError: 'tagLine'

**Comment by Zzaphkiel** [comment]
@SSSctt 

1. 新问题情新开 issue～
2. 您的问题和 #269 一样吗？

**Comment by SSSctt** [comment]
好像是一样的

**Comment by Zzaphkiel** [comment]
@SSSctt v0.11.0 已修复该问题

**Comment by beifangpoi** [comment]
> @SSSctt v0.11.0 已修复该问题

0.11.1 进入对局时报错

**Comment by beifangpoi** [comment]
> @SSSctt v0.11.0 已修复该问题

0.11.1 进入对局时报错 Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 655, in __onGameStatusChanged
  File "app\view\main_window.py", line 722, in __onChampionSelectBegin
  File "app\lol\tools.py", line 707, in parseAllyGameInfo
  File "app\lol\tools.py", line 872, in parseSummonerGameInfo
KeyError: 'puuid'

**Comment by bwj1491977078** [comment]
0.11.1 打开seraphine报错
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 424, in __onLolClientStarted
  File "app\view\main_window.py", line 451, in __startConnector
  File "app\lol\connector.py", line 167, in start
  File "app\common\util.py", line 140, in getPortTokenServerByPid
  File "psutil\__init__.py", line 719, in cmdline
  File "psutil\_pswindows.py", line 730, in wrapper
  File "psutil\_pswindows.py", line 760, in wrapper
psutil.AccessDenied: <function Process.cmdline at 0x000002132BC5E430> retried 33 times, converted to AccessDenied as it's stillreturning [WinError 299] 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。: '(originated from ReadProcessMemory)' (pid=9100)

**Comment by Zzaphkiel** [comment]
新版本 [v0.12.0] 已发布，尝试一下新版本吧~

若再遇到问题请新开 issue。
