### ISSUE TITLE
[BUG] 进入游戏读取界面时远程计算机拒绝网络连接

### ISSUE THREAD

**Issue by Netyulin** [Zzaphkiel/Seraphine#277]
### 问题描述

Traceback (most recent call last):
  File "aiohttp\connector.py", line 992, in _wrap_create_connection
  File "asyncio\base_events.py", line 1025, in create_connection
  File "asyncio\base_events.py", line 1010, in create_connection
  File "asyncio\base_events.py", line 924, in _connect_sock
  File "asyncio\proactor_events.py", line 702, in sock_connect
  File "qasync\_windows.py", line 43, in _process_events
  File "asyncio\windows_events.py", line 599, in finish_connect
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 665, in __onGameStatusChanged
  File "app\view\main_window.py", line 786, in __onGameStart
  File "app\view\main_window.py", line 761, in paintEnemySummonersInfo
  File "app\lol\tools.py", line 748, in parseGameInfoByGameflowSession
  File "app\lol\tools.py", line 867, in parseSummonerGameInfo
  File "app\lol\connector.py", line 73, in wrapper
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 608, in getSummonerById
  File "app\lol\connector.py", line 719, in wrapper
  File "app\lol\connector.py", line 727, in __get
  File "aiohttp\client.py", line 578, in _request
  File "aiohttp\connector.py", line 544, in connect
  File "aiohttp\connector.py", line 911, in _create_connection
  File "aiohttp\connector.py", line 1235, in _create_direct_connection
  File "aiohttp\connector.py", line 1204, in _create_direct_connection
  File "aiohttp\connector.py", line 1000, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:2585 ssl:False [远程计算机拒绝网络连接。]

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.11

### 日志文件

Traceback (most recent call last):
  File "aiohttp\connector.py", line 992, in _wrap_create_connection
  File "asyncio\base_events.py", line 1025, in create_connection
  File "asyncio\base_events.py", line 1010, in create_connection
  File "asyncio\base_events.py", line 924, in _connect_sock
  File "asyncio\proactor_events.py", line 702, in sock_connect
  File "qasync\_windows.py", line 43, in _process_events
  File "asyncio\windows_events.py", line 599, in finish_connect
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 665, in __onGameStatusChanged
  File "app\view\main_window.py", line 786, in __onGameStart
  File "app\view\main_window.py", line 761, in paintEnemySummonersInfo
  File "app\lol\tools.py", line 748, in parseGameInfoByGameflowSession
  File "app\lol\tools.py", line 867, in parseSummonerGameInfo
  File "app\lol\connector.py", line 73, in wrapper
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 608, in getSummonerById
  File "app\lol\connector.py", line 719, in wrapper
  File "app\lol\connector.py", line 727, in __get
  File "aiohttp\client.py", line 578, in _request
  File "aiohttp\connector.py", line 544, in connect
  File "aiohttp\connector.py", line 911, in _create_connection
  File "aiohttp\connector.py", line 1235, in _create_direct_connection
  File "aiohttp\connector.py", line 1204, in _create_direct_connection
  File "aiohttp\connector.py", line 1000, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:2585 ssl:False [远程计算机拒绝网络连接。]

### 出现率（若有）

差不多一半的情况会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢反馈😳，报错的时候客户端还在吗（不是游戏进程）？

**Comment by Zzaphkiel** [comment]
@qq891534 @Netyulin 你们开启 “在游戏时关闭客户端” 功能了吗？
![QQ截图20240317001607](https://github.com/Zzaphkiel/Seraphine/assets/60383222/94b11f24-ecba-4b7e-982d-b7e92d1458d1)

**Comment by qq891534** [comment]
默认是按需，没有设置过。现在已经修改为“从不”

**Comment by Zzaphkiel** [comment]
@qq891534 应该是由于这个功能的开启，进入游戏后客户端被自动关闭了，然而 Seraphine 要与客户端通信所以报错了

**Comment by qq891534** [comment]
![M}$% )OFT8X_OFJ6FA62F~X](https://github.com/Zzaphkiel/Seraphine/assets/74325172/b17c73d9-047d-4352-a066-12096991f7ef)

今日第二局游戏又出现了崩溃的情况

**Comment by Zzaphkiel** [comment]
@qq891534 暂时无法复现该问题

**Comment by longyi995661393** [comment]
![Snipaste_2024-03-17_19-41-54](https://github.com/Zzaphkiel/Seraphine/assets/158059884/332f53b1-f9ca-4f64-b879-3ed9355dc07a)


> @qq891534 暂时无法复现该问题

刚刚我也出现了这个问题

**Comment by RicharYe** [comment]
![2S{KZ3X9 EYG3)}VFVBLXAS](https://github.com/Zzaphkiel/Seraphine/assets/129949451/63c7cc2e-e951-41ba-8bdc-b773053b975d)
更新后我也出现了类似问题，客户端还在，进入游戏后seraphine报错

**Comment by wqdraf2** [comment]
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 658, in __onGameStatusChanged
  File "app\view\main_window.py", line 786, in __onGameStart
  File "app\view\main_window.py", line 776, in sortAllySummonersByGameRole
  File "app\view\game_info_interface.py", line 253, in updateSummonersOrder
KeyError: 3166784323413472

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 665, in __onGameStatusChanged
  File "app\view\main_window.py", line 786, in __onGameStart
  File "app\view\main_window.py", line 776, in sortAllySummonersByGameRole
  File "app\view\game_info_interface.py", line 253, in updateSummonersOrder
KeyError: 3166784323413472

**Comment by Zzaphkiel** [comment]
@Netyulin @qq891534 @RicharYe @wqdraf2 麻烦提供一下游戏大区和模式吧？

**Comment by wqdraf2** [comment]
@Zzaphkiel 你好，只有外服会出现这个问题 我在台服玩的都是排位，国服的话目前没问题 不会一进游戏就弹出这个报错 谢谢你。

**Comment by qq891534** [comment]
> @Netyulin @qq891534 @RicharYe @wqdraf2 麻烦提供一下游戏大区和模式吧？

艾欧尼亚，单双模式。

**Comment by Zzaphkiel** [comment]
> @Zzaphkiel 你好，只有外服会出现这个问题 我在台服玩的都是排位，国服的话目前没问题 不会一进游戏就弹出这个报错 谢谢你。

@wqdraf2 外服排位 100% 会触发报错吗？

**Comment by qq891534** [comment]
> > @Zzaphkiel 你好，只有外服会出现这个问题 我在台服玩的都是排位，国服的话目前没问题 不会一进游戏就弹出这个报错 谢谢你。
> 
> @wqdraf2 外服排位 100% 会触发报错吗？

新版本崩溃问题在国服出现频率还是挺高的，所以目前已经回退到0.10.3版本

**Comment by wqdraf2** [comment]
@Zzaphkiel 外服百分百报错 排队和选英雄没问题 只有选完进游戏就报错 只能重开软件 这些仅限外服(也是14.6版本 之前14.5的话很正常 ) 国服的话我今天玩了6把排位没出现问题 (国服游戏版本14.6)

**Comment by RicharYe** [comment]
我也是艾欧尼亚，单双排，打10把左右可能会碰到1-2次 不是百分百出现。

**Comment by Asahey** [comment]
我也遇到了，从萨勒芬妮启动客户端进去经常会触发一次软件崩溃，不过LOL客户端先启动，再启动萨勒芬妮去连接客户端就不会出现崩溃

**Comment by Zzaphkiel** [comment]
[v0.12.0](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.12.0) 已修复该问题。
