### ISSUE TITLE
[BUG] 多开客户端，无法正常无缝切换连接

### ISSUE THREAD

**Issue by longyi995661393** [Zzaphkiel/Seraphine#278]
### 问题描述

链接：https://pan.baidu.com/s/1hvuqmQzQJA24uuxQX5i6sQ 
提取码：eb0s 
具体情况：多开了三个客户端，Seraphine软件识别到了第一个登录的客户端
然后我依次切换三个客户端都是正常切换了，
然后我开了一局训练模式观察对局详情是否正常
发现正常之后退出游戏，
再次分别一次切换三个客户端
发现无论怎么切换
Seraphine只会识别到被切换的客户端一秒钟之后
瞬间又返回切换到原来的客户端
具体的详情可以下载我上面分享的录制视频观看

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

11.0

### 客户端状态（若有）

大厅中

### 复现方法（若有）

具体情况：多开了三个客户端，Seraphine软件识别到了第一个登录的客户端
然后我依次切换三个客户端都是正常切换了，
然后我开了一局训练模式观察对局详情是否正常
发现正常之后退出游戏，
再次分别一次切换三个客户端
发现无论怎么切换
Seraphine只会识别到被切换的客户端一秒钟之后
瞬间又返回切换到原来的客户端
具体的详情可以下载我上面分享的录制视频观看

### 日志文件

[Seraphine_2024-03-16_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14622356/Seraphine_2024-03-16_ERROR.log)

### 您进行游戏的服务器（若有）

班德尔城

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by longyi995661393** [comment]
另外能否在这个界面增加显示账号ID类似的信息，用于区分是哪个账号
如果只是单单的进程ID，如果多开多了，有点无法区分哪个是哪个账号
![微信图片_20240316115722](https://github.com/Zzaphkiel/Seraphine/assets/158059884/5363b1ca-fc81-4063-9846-b64246da43b0)

**Comment by longyi995661393** [comment]
当多开三个客户端 切换无法正常时
例如：Seraphine一开始识别A号，当我切换B号失败，Seraphine返回识别到A号
此时A号进行游戏，开始选人阶段，对局信息正常
如果用B号进行游戏，开始选人阶段，对局信息开始报错，Seraphine开始失效，需要强退软件
您可以根据我所说的进行复现
报错信息如下：

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 655, in __onGameStatusChanged
  File "app\view\main_window.py", line 722, in __onChampionSelectBegin
  File "app\lol\tools.py", line 703, in parseAllyGameInfo
KeyError: 'myTeam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 655, in __onGameStatusChanged
  File "app\view\main_window.py", line 722, in __onChampionSelectBegin
  File "app\lol\tools.py", line 703, in parseAllyGameInfo
KeyError: 'myTeam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 655, in __onGameStatusChanged
  File "app\view\main_window.py", line 722, in __onChampionSelectBegin
  File "app\lol\tools.py", line 703, in parseAllyGameInfo
KeyError: 'myTeam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 655, in __onGameStatusChanged
  File "app\view\main_window.py", line 722, in __onChampionSelectBegin
  File "app\lol\tools.py", line 703, in parseAllyGameInfo
KeyError: 'myTeam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 655, in __onGameStatusChanged
  File "app\view\main_window.py", line 722, in __onChampionSelectBegin
  File "app\lol\tools.py", line 703, in parseAllyGameInfo
KeyError: 'myTeam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 655, in __onGameStatusChanged
  File "app\view\main_window.py", line 722, in __onChampionSelectBegin
  File "app\lol\tools.py", line 703, in parseAllyGameInfo
KeyError: 'myTeam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 655, in __onGameStatusChanged
  File "app\view\main_window.py", line 722, in __onChampionSelectBegin
  File "app\lol\tools.py", line 703, in parseAllyGameInfo
KeyError: 'myTeam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 655, in __onGameStatusChanged
  File "app\view\main_window.py", line 722, in __onChampionSelectBegin
  File "app\lol\tools.py", line 703, in parseAllyGameInfo
KeyError: 'myTeam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 655, in __onGameStatusChanged
  File "app\view\main_window.py", line 722, in __onChampionSelectBegin
  File "app\lol\tools.py", line 703, in parseAllyGameInfo
KeyError: 'myTeam'

**Comment by Zzaphkiel** [comment]
感谢反馈，现在的代码是在之前基础上加了一些小的改动实现的，但仔细想想感觉多开客户端的场景比正常使用的场景复杂得多，还有很多情况代码没有考虑到。我去试一下修复吧，可能要大改一下代码了😭

**Comment by longyi995661393** [comment]
> 感谢反馈，现在的代码是在之前基础上加了一些小的改动实现的，但仔细想想感觉多开客户端的场景比正常使用的场景复杂得多，还有很多情况代码没有考虑到。我去试一下修复吧，可能要大改一下代码了😭

非常感谢您的付出，期待您的下一次更新！

**Comment by Zzaphkiel** [comment]
[`ead43a5`](https://github.com/Zzaphkiel/Seraphine/commit/ead43a57dc6597ba477635f52d55bba4b99c28f9) 已修复该问题。当前代码在以下场景均正常工作：

1. 启动客户端 A、B，连接客户端 A，随意使用客户端 A、B 进行游戏，游戏中途随意切换客户端 A、B。
2. 启动客户端 A、B，连接客户端 A，退出客户端 A，Seraphine 自动跳转到客户端 B，而不是报错。

需要注意的是，**该功能与 LOL 客户端提供的 “在游戏进行时关闭客户端” 功能不兼容**。

预计今晚 26:00 前发布 v0.11.1，还请耐心等待

**Comment by longyi995661393** [comment]
感谢大佬，速度神速！
