### ISSUE TITLE
[BUG] __updateAvatarIconName 报错

### ISSUE THREAD

**Issue by KazamiYUKI** [Zzaphkiel/Seraphine#301]
### 问题描述

有3个情况。
1.游戏排队时，Seraphine会无限报错。
2.ID旁有个🔒logo。（不确定是否是BUG）
3.游戏中时会三四局左右就报错，要重新打开Seraphine。
由于时间问题，没有保存排队时报错的日志，只有第三种情况的日志。

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.11.1

### 客户端状态（若有）

1.排队进游戏中。2.游戏中客户端隐藏

### 日志文件

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 523, in __onCurrentSummonerProfileChanged
  File "app\view\main_window.py", line 497, in __updateAvatarIconName
AttributeError: 'NoneType' object has no attribute 'get'

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by KazamiYUKI** [comment]
![IWUAIVI_97IS 78__Q$Q9A5](https://github.com/Zzaphkiel/Seraphine/assets/105507398/a453086f-4f80-4393-accf-bb4d7deb76f8)

**Comment by Zzaphkiel** [comment]
感谢反馈。

1. 排队时无限报错的报错信息可否提供一下？或着复现过程？
2. 不是 BUG，有个锁表示这人关了战绩。
3. 和 #277 重复了，现在还在研究。（我这里不复现该问题，解决难度较大）

**Comment by KazamiYUKI** [comment]
1.排队时过程复现即客户端排队时（如一区晚上8点开始人多时），Seraphine和客户端不分先后打开，Seraphine无限报错，若今晚有日志我会提供。
2.了解，谢谢。
3.应该与#277不同，我的情况是快的三四局，慢的一两局，Seraphine会报错（因为开了对局自动接受，某一局没有接受才发现），图1是刚进入客户端未开始游戏时，Seraphine会一直弹请求失败。图2是排队时无限报错的截图。

**Comment by Zzaphkiel** [comment]
了解了，最近有点忙，还请耐心等待修复。

**Comment by KazamiYUKI** [comment]
辛苦了，这是今天排队时无限报错的日志。
Traceback (most recent call last):
  File "app\view\main_window.py", line 451, in __startConnector
  File "app\lol\connector.py", line 175, in start
  File "app\lol\connector.py", line 234, in __initManager
  File "app\lol\connector.py", line 277, in __json_retry_get
app.lol.exceptions.RetryMaximumAttempts: Exceeded maximum retry attempts.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 424, in __onLolClientStarted
  File "app\view\main_window.py", line 456, in __startConnector
  File "app\lol\connector.py", line 209, in close
RuntimeError: super-class __init__() of type LolClientConnector was never called

**Comment by Hpero4** [comment]
排队时lcu service还没起来, 之前修过一次（好像是加了needlcu的装饰器）

**Comment by Keyle777** [comment]
2024-03-29 21:33:19,434 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:34:03,022 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:34:05,216 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:34:06,169 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:34:08,117 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:34:09,599 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:35:14,347 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:35:15,329 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:35:17,249 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:35:18,820 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:35:19,750 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:35:21,182 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:35:22,496 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:35:24,383 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:35:25,201 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:35:26,027 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

2024-03-29 21:36:12,261 - [Connector] ERROR - exit getSummonerGamesByPuuid: Traceback (most recent call last):
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 442, in getSummonerGamesByPuuid
app.lol.exceptions.SummonerGamesNotFound

**Comment by Zzaphkiel** [comment]
@Keyle777 若 0.10.3 版本也同样如此，则说明是服务器问题。

**Comment by KazamiYUKI** [comment]
战绩倒是能显示了，但主要这几天一直出现游戏中途报错，必定出现那种。

**Comment by Zzaphkiel** [comment]
> 战绩倒是能显示了，但主要这几天一直出现游戏中途报错，必定出现那种。

报错内容提供一下？

**Comment by KazamiYUKI** [comment]
@Zzaphkiel 图2和一开始的日志文件就是中途报错的，这两天我可提供一下新的吧。还有个新发现，用低一个版本0.10.3不会报错，一直玩都没报错

**Comment by sliverf0x** [comment]
国服组排玩着就一定出现这个问题，前面几局正常使用，后面报错api无法显示返回信息，不然就是报错误代码提示重启软件，台服单排没出过问题。

**Comment by KazamiYUKI** [comment]
> > 战绩倒是能显示了，但主要这几天一直出现游戏中途报错，必定出现那种。
> 
> 报错内容提供一下？

下面是今天又报错的日志

**Comment by KazamiYUKI** [comment]
> > 战绩倒是能显示了，但主要这几天一直出现游戏中途报错，必定出现那种。
> 
> 报错内容提供一下？

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 655, in __onGameStatusChanged
  File "app\view\main_window.py", line 722, in __onChampionSelectBegin
  File "app\lol\tools.py", line 707, in parseAllyGameInfo
  File "app\lol\tools.py", line 874, in parseSummonerGameInfo
  File "app\lol\tools.py", line 550, in parseRankInfo
KeyError: 'queueMap'
这是今天又出现的报错日志，一局没打完就出现了

**Comment by opkhkh** [comment]
> ![屏幕截图 2024-03-29 213544](https://private-user-images.githubusercontent.com/90593019/318059617-55a1cc78-69fe-464a-bd90-037363ae2ccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTc2NjIsIm5iZiI6MTcxMjY1NzM2MiwicGF0aCI6Ii85MDU5MzAxOS8zMTgwNTk2MTctNTVhMWNjNzgtNjlmZS00NjRhLWJkOTAtMDM3MzYzYWUyY2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDEwMDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5N2ZiYWIwOTA0MDRlOTJiYjRhNzgwNDFmYjJlZGFlMzhjMDY0ZDU2NWIxZWY3MjRjYWViZjViYjQzYzFkMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oT4sE-xZmNjEZA_0Mqi6h87iXg1Pg4WbIfj7u9qQqtc) ![屏幕截图 2024-03-29 213547](https://private-user-images.githubusercontent.com/90593019/318059628-0bb7cb2e-3ca3-4593-ad95-a486ea6a8046.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTc2NjIsIm5iZiI6MTcxMjY1NzM2MiwicGF0aCI6Ii85MDU5MzAxOS8zMTgwNTk2MjgtMGJiN2NiMmUtM2NhMy00NTkzLWFkOTUtYTQ4NmVhNmE4MDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDEwMDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0YjU0ODNlMzQ4MTNmZTE5MGFhOTQyNDFlMjNkOGVmZmZhZWM3ZGRkOTM3NzM4M2E2YWNjOTA5NzI4MjEwYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KLIn3CyEsalHt_3WMtFYwWh5M845QpCwghfCow-fVxE) 基本不可用状态，出现频率非常高

当Seraphine查不到战绩的时候，此时去LOL客户端查看对局记录，同样查不到，可能是LOL官方那边的原因

**Comment by Hpero4** [comment]
https://github.com/Zzaphkiel/Seraphine/issues/301#issuecomment-2035321217
这个我复现了, 初步来看应该是网络问题, 在特定条件(弱网)下 /lol-ranked/v1/ranked-stats/会不响应 或是 响应带有errorCode的异常内容, 导致后续解析渲染的逻辑出问题;

review代码发现此问题以前修过一次, 但是未做系统性的异常抛出再捕获, 导致后续再调用这个接口时没有意识到可能存在的潜在风险; 

该问题将在下个版本中修复;

![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/58d8fba7-7f9b-40d2-ab26-fa96ccd17aa1)

**Comment by Zzaphkiel** [comment]
[v0.12.0](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.12.0) 已修复该问题。
