### ISSUE TITLE
[BUG] 启动客户端出现“客户端无法与登录队列进行通讯，平台也许在维护中”时程序崩溃

### ISSUE THREAD

**Issue by Ghosthh2** [Zzaphkiel/Seraphine#309]
## 我的环境
我这边网络情况会导致需要多次登录才能成功到大厅的，因此我认为只需要处理当出现这种情况时，Seraphine不会直接报错强行退出就好
## 报错信息
Traceback (most recent call last):
  File "app\view\main_window.py", line 451, in __startConnector
  File "app\lol\connector.py", line 175, in start
  File "app\lol\connector.py", line 230, in __initManager
  File "app\lol\connector.py", line 277, in __json_retry_get
app.lol.exceptions.RetryMaximumAttempts: Exceeded maximum retry attempts.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 424, in __onLolClientStarted
  File "app\view\main_window.py", line 456, in __startConnector
  File "app\lol\connector.py", line 209, in close
RuntimeError: super-class __init__() of type LolClientConnector was never called
## LOL客户端截图
![image](https://github.com/Zzaphkiel/Seraphine/assets/41540922/233a8dd4-2021-4bf8-852f-013730f85b7f)

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.11.1

### 客户端状态（若有）

选区后登录到大厅的过程中

### 复现方法（若有）

可能开TUN模式的翻墙并使用全局模式时可以复现吧。

### 日志文件

[Seraphine_2024-03-29_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14804621/Seraphine_2024-03-29_ERROR.log)

### 您进行游戏的服务器（若有）

黑色玫瑰

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢反馈。之前没这个问题的，0.10.0 重构之后引入的 BUG，现在仓库代码已经修复了。
