### ISSUE TITLE
[BUG] KeyError: 'profileIconId'

### ISSUE THREAD

**Issue by GreenMope** [Zzaphkiel/Seraphine#315]
### 问题描述

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 632, in __switchToCareerInterface
  File "app\view\career_interface.py", line 371, in updateInterface
  File "app\lol\tools.py", line 108, in parseSummonerData
KeyError: 'profileIconId'

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.11.1

### 日志文件

2024-04-02 11:23:10,177 - [MainWindow] CRITICAL - Seraphine started, version: 0.11.1
2024-04-02 11:23:11,489 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-04-02 11:23:11,489 - [MainWindow] CRITICAL - Seraphine listerners started
2024-04-02 11:23:11,654 - [MainWindow] CRITICAL - Seraphine initialized
2024-04-02 11:23:12,597 - [Connector] CRITICAL - connector started, server: HN1
2024-04-02 12:02:50,304 - [MainWindow] CRITICAL - Seraphine started, version: 0.11.1
2024-04-02 12:02:51,315 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-04-02 12:02:51,315 - [MainWindow] CRITICAL - Seraphine listerners started
2024-04-02 12:02:51,469 - [MainWindow] CRITICAL - Seraphine initialized
2024-04-02 12:02:52,273 - [Connector] CRITICAL - connector started, server: HN1
2024-04-02 12:18:39,384 - [Connector] ERROR - getItemIconPath, iconId: 3191
2024-04-02 12:18:43,106 - [Connector] ERROR - getItemIconPath, iconId: 2424

### 您进行游戏的服务器（若有）

峡谷之巅

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
可以提供一下复现方式吗？

**Comment by GreenMope** [comment]
> 可以提供一下复现方式吗？

下次一定

**Comment by Chouxk** [comment]
同样错误，提供复现思路，先使用wegame，再使用Seraphine

**Comment by Chouxk** [comment]
同样错误，提供复现思路，先使用Seraphine，然后使用wegame，最后Seraphine

**Comment by Zzaphkiel** [comment]
尝试一下 [v0.12.0](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.12.0) 吧~

若再遇到问题请重新开 issue。
