### ISSUE TITLE
[BUG] KeyError: 'participantIdentities'

### ISSUE THREAD

**Issue by GreenMope** [Zzaphkiel/Seraphine#318]
### 问题描述

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 655, in __onGameStatusChanged
  File "app\view\main_window.py", line 722, in __onChampionSelectBegin
  File "app\lol\tools.py", line 707, in parseAllyGameInfo
  File "app\lol\tools.py", line 903, in parseSummonerGameInfo
  File "app\lol\tools.py", line 904, in <listcomp>
  File "app\lol\tools.py", line 466, in getTeammates
KeyError: 'participantIdentities'

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.11.1

### 客户端状态（若有）

关闭

### 复现方法（若有）

打完一局对局，关闭游戏，然后从右下角图标打开，就提示这个了

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢，出现问题频率大嘛？

**Comment by GreenMope** [comment]
> 感谢，出现问题频率大嘛？

各种不同问题出现的频率还是很大的，基本上每次用都会出问题...
尤其是在选人阶段使用以后，进入游戏后会导致客户端消失，然后提示连接不到客户端，但是游戏正常运行
小队语音也会随着客户端消失一起消失

客户端消失是一个比较常见的问题

**Comment by MVPjoker** [comment]
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 665, in __onGameStatusChanged
  File "app\view\main_window.py", line 786, in __onGameStart
  File "app\view\main_window.py", line 761, in paintEnemySummonersInfo
  File "app\lol\tools.py", line 748, in parseGameInfoByGameflowSession
  File "app\lol\tools.py", line 872, in parseSummonerGameInfo
KeyError: 'puuid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 658, in __onGameStatusChanged
  File "app\view\main_window.py", line 786, in __onGameStart
  File "app\view\main_window.py", line 761, in paintEnemySummonersInfo
  File "app\lol\tools.py", line 748, in parseGameInfoByGameflowSession
  File "app\lol\tools.py", line 872, in parseSummonerGameInfo
KeyError: 'puuid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 674, in __onGameStatusChanged
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\career_interface.py", line 356, in refresh
  File "app\view\career_interface.py", line 369, in updateInterface
  File "app\lol\connector.py", line 73, in wrapper
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 383, in getSummonerByPuuid
  File "app\lol\connector.py", line 717, in wrapper
ReferenceError

我今天出现这个报错，不知道什么原因
