### ISSUE TITLE
[BUG] 游戏结束后报错

### ISSUE THREAD

**Issue by chasiopen** [Zzaphkiel/Seraphine#320]
### 问题描述

游戏结算之后报错，出现了很多次了。

（并不清楚是游戏中还是游戏结算时，反正游戏结束之后看软件已经报错了）

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.11.1

### 日志文件

Traceback (most recent call last):
  File "aiohttp\connector.py", line 992, in _wrap_create_connection
  File "asyncio\base_events.py", line 1025, in create_connection
  File "asyncio\base_events.py", line 1010, in create_connection
  File "asyncio\base_events.py", line 924, in _connect_sock
  File "asyncio\proactor_events.py", line 702, in sock_connect
  File "qasync\_windows.py", line 43, in _process_events
  File "asyncio\windows_events.py", line 599, in finish_connect
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 658, in __onGameStatusChanged
  File "app\view\main_window.py", line 786, in __onGameStart
  File "app\view\main_window.py", line 761, in paintEnemySummonersInfo
  File "app\lol\tools.py", line 748, in parseGameInfoByGameflowSession
  File "app\lol\tools.py", line 867, in parseSummonerGameInfo
  File "app\lol\connector.py", line 73, in wrapper
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 608, in getSummonerById
  File "app\lol\connector.py", line 719, in wrapper
  File "app\lol\connector.py", line 727, in __get
  File "aiohttp\client.py", line 578, in _request
  File "aiohttp\connector.py", line 544, in connect
  File "aiohttp\connector.py", line 911, in _create_connection
  File "aiohttp\connector.py", line 1235, in _create_direct_connection
  File "aiohttp\connector.py", line 1204, in _create_direct_connection
  File "aiohttp\connector.py", line 1000, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:5331 ssl:False [远程计算机拒绝网络连接。]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aiohttp\connector.py", line 992, in _wrap_create_connection
  File "asyncio\base_events.py", line 1025, in create_connection
  File "asyncio\base_events.py", line 1010, in create_connection
  File "asyncio\base_events.py", line 924, in _connect_sock
  File "asyncio\proactor_events.py", line 702, in sock_connect
  File "qasync\_windows.py", line 43, in _process_events
  File "asyncio\windows_events.py", line 599, in finish_connect
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 665, in __onGameStatusChanged
  File "app\view\main_window.py", line 786, in __onGameStart
  File "app\view\main_window.py", line 761, in paintEnemySummonersInfo
  File "app\lol\tools.py", line 748, in parseGameInfoByGameflowSession
  File "app\lol\tools.py", line 867, in parseSummonerGameInfo
  File "app\lol\connector.py", line 73, in wrapper
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 608, in getSummonerById
  File "app\lol\connector.py", line 719, in wrapper
  File "app\lol\connector.py", line 727, in __get
  File "aiohttp\client.py", line 578, in _request
  File "aiohttp\connector.py", line 544, in connect
  File "aiohttp\connector.py", line 911, in _create_connection
  File "aiohttp\connector.py", line 1235, in _create_direct_connection
  File "aiohttp\connector.py", line 1204, in _create_direct_connection
  File "aiohttp\connector.py", line 1000, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:5331 ssl:False [远程计算机拒绝网络连接。]

### 您进行游戏的服务器（若有）

影流

### 出现率（若有）

非常低的概率会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢反馈，和 #277 重复了。最近太忙没时间修 BUG，可以暂时用一下 v0.10.3 版本。
