### ISSUE TITLE
[Question] Traceback (most recent call last)

### ISSUE THREAD

**Issue by Biutao** [Zzaphkiel/Seraphine#327]
### 问题描述

Traceback (most recent call last):
  File "app\view\main_window.py", line 451, in __startConnector
  File "app\lol\connector.py", line 175, in start
  File "app\lol\connector.py", line 234, in __initManager
  File "app\lol\connector.py", line 277, in __json_retry_get
app.lol.exceptions.RetryMaximumAttempts: Exceeded maximum retry attempts.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 424, in __onLolClientStarted
  File "app\view\main_window.py", line 456, in __startConnector
  File "app\lol\connector.py", line 209, in close
RuntimeError: super-class __init__() of type LolClientConnector was never called
弹出这信息之后软件就关闭了，是因为什么啊，求大佬指点。软件我重装过好几次了，游戏也重装过

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
先用 0.10.3 版本，或者在客户端完全打开之后再开 Seraphine。

**Comment by Biutao** [comment]
> 先用 0.10.3 版本，或者在客户端完全打开之后再开 Seraphine。

多谢解答

**Comment by Biutao** [comment]
> 仓库代码已经把这 BUG 已经修过了，等找时间把最近几个 BUG 统一修了之后再发新版本哈

支持 加油。越做越好👍
