### ISSUE TITLE
[BUG] in getNameMapByQueueId KeyError: 'Ranked Solo/Duo'

### ISSUE THREAD

**Issue by Neekodesu** [Zzaphkiel/Seraphine#336]
### 问题描述

Sorry I don't speak chinese. BUG:
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 655, in __onGameStatusChanged
  File "app\view\main_window.py", line 722, in __onChampionSelectBegin
  File "app\lol\tools.py", line 707, in parseAllyGameInfo
  File "app\lol\tools.py", line 899, in parseSummonerGameInfo
  File "app\lol\tools.py", line 170, in parseGameData
  File "app\lol\connector.py", line 831, in getNameMapByQueueId
KeyError: 'Ranked Solo/Duo'

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

Latest

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Hpero4** [comment]
@Neekodesu Thank you for your feedback! Based on the information you have provided so far, we are unable to pinpoint the issue at the moment. 
1. May I ask which server you are using? 
2. Additionally, could you please inform us when this bug first occurred (what actions were being performed at the time)? 
3. Does this bug appear every time these specific actions are taken?

**Comment by Neekodesu** [comment]
1. EUW
2. I just saw Seraphine on github and wanted to test it, but whenever I try to use it, it just shows that when clicking on my account button. 
![image](https://github.com/Zzaphkiel/Seraphine/assets/47283957/1bdfd8e9-d797-4920-b911-ec182f8854f4)

3. Yes.

**Comment by Zzaphkiel** [comment]
dde83a7 fixed it.
