### ISSUE TITLE
[BUG] 使用的时候有时候会闪退，并且会设置不了符文，进游戏把符文给换了

### ISSUE THREAD

**Issue by bujianxingguang** [Zzaphkiel/Seraphine#348]
### 问题描述

使用的时候到选英雄界面会闪退，重连之后可以继续但是会设置不了符文，进游戏把选好的符文给换成默认的

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.11.1

### 客户端状态（若有）

禁用选取英雄

### 复现方法（若有）

Traceback (most recent call last):
  File "app\view\main_window.py", line 451, in __startConnector
  File "app\lol\connector.py", line 175, in start
  File "app\lol\connector.py", line 230, in __initManager
  File "app\lol\connector.py", line 277, in __json_retry_get
app.lol.exceptions.RetryMaximumAttempts: Exceeded maximum retry attempts.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 424, in __onLolClientStarted
  File "app\view\main_window.py", line 456, in __startConnector
  File "app\lol\connector.py", line 209, in close
RuntimeError: super-class __init__() of type LolClientConnector was never called

### 日志文件

2024-05-01 19:54:56,715 - [MainWindow] CRITICAL - Seraphine started, version: 0.11.1
2024-05-01 19:54:57,461 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-05-01 19:54:57,461 - [MainWindow] CRITICAL - Seraphine listerners started
2024-05-01 19:54:57,565 - [MainWindow] CRITICAL - Seraphine initialized
2024-05-01 19:56:19,718 - [MainWindow] CRITICAL - Seraphine started, version: 0.11.1
2024-05-01 19:56:20,366 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-05-01 19:56:20,366 - [MainWindow] CRITICAL - Seraphine listerners started
2024-05-01 19:56:20,467 - [MainWindow] CRITICAL - Seraphine initialized
2024-05-01 19:58:20,954 - [MainWindow] CRITICAL - Seraphine started, version: 0.11.1
2024-05-01 19:58:21,598 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-05-01 19:58:21,599 - [MainWindow] CRITICAL - Seraphine listerners started
2024-05-01 19:58:21,705 - [MainWindow] CRITICAL - Seraphine initialized
2024-05-01 20:00:57,710 - [MainWindow] CRITICAL - Seraphine started, version: 0.11.1
2024-05-01 20:00:58,399 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-05-01 20:00:58,399 - [MainWindow] CRITICAL - Seraphine listerners started
2024-05-01 20:00:58,505 - [MainWindow] CRITICAL - Seraphine initialized
-------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "app\view\main_window.py", line 451, in __startConnector
  File "app\lol\connector.py", line 175, in start
  File "app\lol\connector.py", line 230, in __initManager
  File "app\lol\connector.py", line 277, in __json_retry_get
app.lol.exceptions.RetryMaximumAttempts: Exceeded maximum retry attempts.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 424, in __onLolClientStarted
  File "app\view\main_window.py", line 456, in __startConnector
  File "app\lol\connector.py", line 209, in close
RuntimeError: super-class __init__() of type LolClientConnector was never called

### 您进行游戏的服务器（若有）

弗雷尔卓德

### 出现率（若有）

差不多一半的情况会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
这问题已经出现好久了 (见 #158)，新版本（仓库代码）可能会解决这一问题（至少我高强度用了两天没遇到），目前还在测试中
