### ISSUE TITLE
[BUG] （游戏打开就崩溃了）

### ISSUE THREAD

**Issue by libiexie** [Zzaphkiel/Seraphine#349]
### 问题描述

游戏还没打开软件就崩溃了，已经下了好几遍软件了但是新下载的设置就是调好的，找不到配置文件

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.11.1

### 客户端状态（若有）

将要开启状态

### 复现方法（若有）

先点开软件然后用软件启动页的快捷打开游戏

### 日志文件

Traceback (most recent call last):
  File "app\view\main_window.py", line 451, in __startConnector
  File "app\lol\connector.py", line 175, in start
  File "app\lol\connector.py", line 230, in __initManager
  File "app\lol\connector.py", line 277, in __json_retry_get
app.lol.exceptions.RetryMaximumAttempts: Exceeded maximum retry attempts.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 424, in __onLolClientStarted
  File "app\view\main_window.py", line 456, in __startConnector
  File "app\lol\connector.py", line 209, in close
RuntimeError: super-class __init__() of type LolClientConnector was never called

### 您进行游戏的服务器（若有）

德玛西亚

### 出现率（若有）

差不多一半的情况会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by libiexie** [comment]
> 您可以尝试等待**客户端完全启动好**后再打开 Seraphine，新版本将修复这一问题。

还有设置已经启用了打开软件自动启动游戏，但是还是没有用，打开软件游戏并没有反应

**Comment by Zzaphkiel** [comment]
> > 您可以尝试等待**客户端完全启动好**后再打开 Seraphine，新版本将修复这一问题。
> 
> 还有设置已经启用了打开软件自动启动游戏，但是还是没有用，打开软件游戏并没有反应

见 #291，仓库代码已修复该问题，暂时等待新版本吧（或者暂时使用 0.10.3）
