### ISSUE TITLE
[BUG]  斗魂竞技场相关战绩在详情页会直接报错

### ISSUE THREAD

**Issue by kiriYui0** [Zzaphkiel/Seraphine#350]
### 问题描述

斗魂竞技场对局，点击对局查看详情会弹窗提示异常
![%7BE9D5E134-69CE-49b8-B44E-46E3AE6D2D4B%7D](https://github.com/Zzaphkiel/Seraphine/assets/59152251/0787554d-e592-4676-a385-bd46d72e714a)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.11.1

### 日志文件

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 436, in __onLolClientStarted
  File "app\lol\connector.py", line 73, in wrapper
  File "app\lol\connector.py", line 50, in wrapper
  File "app\lol\connector.py", line 306, in getInstallFolder
  File "app\lol\connector.py", line 717, in wrapper
ReferenceError

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
见 #346

**Comment by kiriYui0** [comment]
> 见 #346

sry，之前没筛选已经关闭的bug
