### ISSUE TITLE
[BUG] 启动外服客户端后报错

### ISSUE THREAD

**Issue by Swaynani** [Zzaphkiel/Seraphine#352]
### 问题描述

打开软件报错 在不开启LOL客户端的时候打开不会报错,但是一旦打开客户端就会报错,在开启客户端的情况下会直接报错/
![QQ截图20240504055351](https://github.com/Zzaphkiel/Seraphine/assets/57582753/6b62a946-d9ac-4527-94e8-9b18fc838f63)
错误提示
  Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 446, in __onLolClientStarted
  File "app\view\main_window.py", line 500, in __startConnector
  File "app\lol\connector.py", line 224, in start
AttributeError: 'NoneType' object has no attribute 'lower'

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.12.0

### 复现方法（若有）

新版本每次都这样

### 日志文件

2024-05-04 04:50:55,448 - [MainWindow] CRITICAL - Seraphine started, version: 0.12.0
2024-05-04 04:50:56,184 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-05-04 04:50:56,184 - [MainWindow] CRITICAL - Seraphine listerners started
2024-05-04 04:50:56,302 - [MainWindow] CRITICAL - Seraphine initialized
2024-05-04 04:50:56,574 - [Crash] ERROR - connector call_stack -------------- ↓
2024-05-04 04:50:56,574 - [Crash] ERROR - connector call_stack -------------- ↑
2024-05-04 04:50:56,574 - [Crash] ERROR - SearchInterface(
  puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0
)
2024-05-04 04:50:56,575 - [Crash] ERROR - GameInfoInterface(
  allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0
)
2024-05-04 04:50:56,575 - [Crash] ERROR - CareerInterface(
  currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, rankInfo(list)=[['单 / 双排'], ['灵活排位']], games(list)=[], loadGamesTask(NoneType)=None
)
2024-05-04 04:50:56,575 - [Crash] ERROR - AuxiliaryInterface(
  
)
2024-05-04 04:50:56,576 - [Crash] ERROR - SettingInterface(
  
)
2024-05-04 04:51:20,719 - [MainWindow] CRITICAL - Seraphine started, version: 0.12.0
2024-05-04 04:51:21,444 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-05-04 04:51:21,444 - [MainWindow] CRITICAL - Seraphine listerners started
2024-05-04 04:51:21,558 - [MainWindow] CRITICAL - Seraphine initialized
2024-05-04 04:51:21,832 - [Crash] ERROR - connector call_stack -------------- ↓
2024-05-04 04:51:21,832 - [Crash] ERROR - connector call_stack -------------- ↑
2024-05-04 04:51:21,832 - [Crash] ERROR - SearchInterface(
  puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0
)
2024-05-04 04:51:21,833 - [Crash] ERROR - GameInfoInterface(
  allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0
)
2024-05-04 04:51:21,833 - [Crash] ERROR - CareerInterface(
  currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, rankInfo(list)=[['单 / 双排'], ['灵活排位']], games(list)=[], loadGamesTask(NoneType)=None
)
2024-05-04 04:51:21,833 - [Crash] ERROR - AuxiliaryInterface(
  
)
2024-05-04 04:51:21,833 - [Crash] ERROR - SettingInterface(
  
)
2024-05-04 05:11:27,731 - [MainWindow] CRITICAL - Seraphine started, version: 0.12.0
2024-05-04 05:11:28,506 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-05-04 05:11:28,506 - [MainWindow] CRITICAL - Seraphine listerners started
2024-05-04 05:11:28,625 - [MainWindow] CRITICAL - Seraphine initialized
2024-05-04 05:11:28,896 - [Crash] ERROR - connector call_stack -------------- ↓
2024-05-04 05:11:28,896 - [Crash] ERROR - connector call_stack -------------- ↑
2024-05-04 05:11:28,896 - [Crash] ERROR - SearchInterface(
  puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0
)
2024-05-04 05:11:28,897 - [Crash] ERROR - GameInfoInterface(
  allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0
)
2024-05-04 05:11:28,897 - [Crash] ERROR - CareerInterface(
  currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, rankInfo(list)=[['单 / 双排'], ['灵活排位']], games(list)=[], loadGamesTask(NoneType)=None
)
2024-05-04 05:11:28,897 - [Crash] ERROR - AuxiliaryInterface(
  
)
2024-05-04 05:11:28,898 - [Crash] ERROR - SettingInterface(
  
)
2024-05-04 05:13:13,628 - [MainWindow] CRITICAL - Seraphine started,
2024-05-04 05:13:14,371 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-05-04 05:13:14,371 - [MainWindow] CRITICAL - Seraphine listerners started
2024-05-04 05:13:14,485 - [MainWindow] CRITICAL - Seraphine initialized
2024-05-04 05:13:14,754 - [Crash] ERROR - connector call_stack -------------- ↓
2024-05-04 05:13:14,755 - [Crash] ERROR - connector call_stack -------------- ↑
2024-05-04 05:13:14,755 - [Crash] ERROR - SearchInterface(
  puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0
)
2024-05-04 05:13:14,755 - [Crash] ERROR - GameInfoInterface(
  allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0
)
2024-05-04 05:13:14,755 - [Crash] ERROR - CareerInterface(
  currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, rankInfo(list)=[['单 / 双排'], ['灵活排位']], games(list)=[], loadGamesTask(NoneType)=None
)
2024-05-04 05:13:14,756 - [Crash] ERROR - AuxiliaryInterface(
  
)
2024-05-04 05:13:14,756 - [Crash] ERROR - SettingInterface(
  
)
2024-05-04 05:13:36,327 - [MainWindow] CRITICAL - Seraphine started, version: 0.12.0
2024-05-04 05:13:37,038 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-05-04 05:13:37,038 - [MainWindow] CRITICAL - Seraphine listerners started
2024-05-04 05:13:37,156 - [MainWindow] CRITICAL - Seraphine initialized
2024-05-04 05:13:37,414 - [Crash] ERROR - connector call_stack -------------- ↓
2024-05-04 05:13:37,414 - [Crash] ERROR - connector call_stack -------------- ↑
2024-05-04 05:13:37,415 - [Crash] ERROR - SearchInterface(
  puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0
)
2024-05-04 05:13:37,415 - [Crash] ERROR - GameInfoInterface(
  allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0
)
2024-05-04 05:13:37,416 - [Crash] ERROR - CareerInterface(
  currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, rankInfo(list)=[['单 / 双排'], ['灵活排位']], games(list)=[], loadGamesTask(NoneType)=None
)
2024-05-04 05:13:37,416 - [Crash] ERROR - AuxiliaryInterface(
  
)
2024-05-04 05:13:37,416 - [Crash] ERROR - SettingInterface(
  
)
2024-05-04 05:14:27,876 - [MainWindow] CRITICAL - Seraphine started, version: 0.12.0
2024-05-04 05:14:28,607 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-05-04 05:14:28,607 - [MainWindow] CRITICAL - Seraphine listerners started
2024-05-04 05:14:28,724 - [MainWindow] CRITICAL - Seraphine initialized
2024-05-04 05:14:28,982 - [Crash] ERROR - connector call_stack -------------- ↓
2024-05-04 05:14:28,982 - [Crash] ERROR - connector call_stack -------------- ↑
2024-05-04 05:14:28,982 - [Crash] ERROR - SearchInterface(
  puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0
)
2024-05-04 05:14:28,983 - [Crash] ERROR - GameInfoInterface(
  allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0
)
2024-05-04 05:14:28,983 - [Crash] ERROR - CareerInterface(
  currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, rankInfo(list)=[['单 / 双排'], ['灵活排位']], games(list)=[], loadGamesTask(NoneType)=None
)
2024-05-04 05:14:28,984 - [Crash] ERROR - AuxiliaryInterface(
  
)
2024-05-04 05:14:28,984 - [Crash] ERROR - SettingInterface(
  
)
2024-05-04 05:49:42,268 - [MainWindow] CRITICAL - Seraphine started, version: 0.12.0
2024-05-04 05:49:43,087 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-05-04 05:49:43,087 - [MainWindow] CRITICAL - Seraphine listerners started
2024-05-04 05:49:43,199 - [MainWindow] CRITICAL - Seraphine initialized
2024-05-04 05:51:48,040 - [Crash] ERROR - connector call_stack -------------- ↓
2024-05-04 05:51:48,040 - [Crash] ERROR - connector call_stack -------------- ↑
2024-05-04 05:51:48,041 - [Crash] ERROR - SearchInterface(
  puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0
)
2024-05-04 05:51:48,041 - [Crash] ERROR - GameInfoInterface(
  allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0
)
2024-05-04 05:51:48,042 - [Crash] ERROR - CareerInterface(
  currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, rankInfo(list)=[['单 / 双排'], ['灵活排位']], games(list)=[], loadGamesTask(NoneType)=None
)
2024-05-04 05:51:48,042 - [Crash] ERROR - AuxiliaryInterface(
  
)
2024-05-04 05:51:48,042 - [Crash] ERROR - SettingInterface(
  
)
2024-05-04 05:52:23,443 - [MainWindow] CRITICAL - Seraphine started, version: 0.12.0
2024-05-04 05:52:24,080 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-05-04 05:52:24,080 - [MainWindow] CRITICAL - Seraphine listerners started
2024-05-04 05:52:24,179 - [MainWindow] CRITICAL - Seraphine initialized
2024-05-04 05:52:24,386 - [Crash] ERROR - connector call_stack -------------- ↓
2024-05-04 05:52:24,386 - [Crash] ERROR - connector call_stack -------------- ↑
2024-05-04 05:52:24,387 - [Crash] ERROR - SearchInterface(
  puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0
)
2024-05-04 05:52:24,387 - [Crash] ERROR - GameInfoInterface(
  allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0
)
2024-05-04 05:52:24,387 - [Crash] ERROR - CareerInterface(
  currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, rankInfo(list)=[['单 / 双排'], ['灵活排位']], games(list)=[], loadGamesTask(NoneType)=None
)
2024-05-04 05:52:24,387 - [Crash] ERROR - AuxiliaryInterface(
  
)
2024-05-04 05:52:24,387 - [Crash] ERROR - SettingInterface(
  
)
2024-05-04 05:53:46,645 - [MainWindow] CRITICAL - Seraphine started, version: 0.12.0
2024-05-04 05:53:47,286 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-05-04 05:53:47,286 - [MainWindow] CRITICAL - Seraphine listerners started
2024-05-04 05:53:47,388 - [MainWindow] CRITICAL - Seraphine initialized
2024-05-04 05:53:47,598 - [Crash] ERROR - connector call_stack -------------- ↓
2024-05-04 05:53:47,598 - [Crash] ERROR - connector call_stack -------------- ↑
2024-05-04 05:53:47,598 - [Crash] ERROR - SearchInterface(
  puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0
)
2024-05-04 05:53:47,599 - [Crash] ERROR - GameInfoInterface(
  allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0
)
2024-05-04 05:53:47,599 - [Crash] ERROR - CareerInterface(
  currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, rankInfo(list)=[['单 / 双排'], ['灵活排位']], games(list)=[], loadGamesTask(NoneType)=None
)
2024-05-04 05:53:47,599 - [Crash] ERROR - AuxiliaryInterface(
  
)
2024-05-04 05:53:47,599 - [Crash] ERROR - SettingInterface(
  
)

### 您进行游戏的服务器（若有）

台服

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by chasiopen** [comment]
类似的问题，直接软件启动不起来。
自动下载更新后，一打开软件就报错。
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 58, in <module>
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 42, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "win32com\__init__.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pythoncom.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pywintypes.py", line 126, in <module>
  File "pywintypes.py", line 47, in __import_pywin32_system_module__
ImportError: Module 'pywintypes' isn't in frozen sys.path ['D:\\Seraphine\\base_library.zip', 'D:\\Seraphine\\lib-dynload', 'D:\\Seraphine']
![image](https://github.com/Zzaphkiel/Seraphine/assets/35827956/d425854a-25db-4f25-a607-38797851bd45)

重新下载压缩包解压之后正常。

**Comment by jiayingming233** [comment]
我也出现了同样的问题，运行的是韩服，更新之前是正常的。

**Comment by Zzaphkiel** [comment]
@jiayingming233 @Swaynani 已定位该问题，下午会发新版本修复它。

@chasiopen 软件内下载的内容和 GitHub 发布的内容是完全一样的，只能怀疑是杀毒软件在下载过程中把什么东西干掉了。

**Comment by Zzaphkiel** [comment]
[v0.12.1](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.12.1) 修复了该问题。
