### ISSUE TITLE
[BUG] 查看斗魂竞技场报错

### ISSUE THREAD

**Issue by Cat0x1** [Zzaphkiel/Seraphine#360]
### 问题描述

点击斗魂竞技场历史战绩报错异常退出Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\search_interface.py", line 1232, in __onGameTabClicked
  File "app\view\search_interface.py", line 1240, in updateGameDetailView
  File "app\lol\connector.py", line 114, in wrapper
  File "app\lol\connector.py", line 88, in wrapper
  File "app\lol\connector.py", line 527, in getGameDetailByGameId
  File "app\lol\connector.py", line 47, in wrapper
  File "app\lol\connector.py", line 918, in __get
  File "aiohttp\client.py", line 425, in _request
RuntimeError: Session is closed

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.12.2

### 复现方法（若有）

![image](https://github.com/Zzaphkiel/Seraphine/assets/58590403/3231a873-a163-4fce-8f72-df027157f400)

### 日志文件

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\search_interface.py", line 1232, in __onGameTabClicked
  File "app\view\search_interface.py", line 1240, in updateGameDetailView
  File "app\lol\connector.py", line 114, in wrapper
  File "app\lol\connector.py", line 88, in wrapper
  File "app\lol\connector.py", line 527, in getGameDetailByGameId
  File "app\lol\connector.py", line 47, in wrapper
  File "app\lol\connector.py", line 918, in __get
  File "aiohttp\client.py", line 425, in _request
RuntimeError: Session is closed

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
等游戏结束，客户端重新出现之后就不会报错了
