### ISSUE TITLE
[BUG]  突然报错然后退出

### ISSUE THREAD

**Issue by kissgo** [Zzaphkiel/Seraphine#367]
### 问题描述

突然弹窗然后报错，在多个阶段均出现过，但是频率不算高，可能最多一天一次，重启之后就好了
Traceback (most recent call last):
  File "app\lol\listener.py", line 32, in run
  File "app\common\util.py", line 99, in getLolClientPids
  File "subprocess.py", line 415, in check_output
  File "subprocess.py", line 493, in run
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
PermissionError: [WinError 5] 拒绝访问。

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.12.2

### 客户端状态（若有）

游戏大厅，队列中，ban英雄阶段都有出现过

### 复现方法（若有）

没有办法，每次都是随机出现的，有时候在游戏大厅挂机就会弹出来，有时候在排队就会有，ban英雄阶段也出现过，但是游戏中好像没有（可能有我也没发现）

### 日志文件

[Seraphine_2024-05-12_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/15286347/Seraphine_2024-05-12_ERROR.log)

### 您进行游戏的服务器（若有）

诺克萨斯

### 出现率（若有）

非常低的概率会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by kissgo** [comment]
出现了一个新的
Traceback (most recent call last):
  File "app\lol\listener.py", line 32, in run
  File "app\common\util.py", line 99, in getLolClientPids
  File "subprocess.py", line 415, in check_output
  File "subprocess.py", line 516, in run
subprocess.CalledProcessError: Command 'tasklist /FI "imagename eq LeagueClientUx.exe" /NH' returned non-zero exit status 1.

**Comment by Hpero4** [comment]
@kissgo 请问是在自己电脑上玩还是网吧玩?

**Comment by kissgo** [comment]
> @kissgo 请问是在自己电脑上玩还是网吧玩?

自己电脑

**Comment by kissgo** [comment]
![image](https://github.com/Zzaphkiel/Seraphine/assets/48850987/7590b96b-0f7e-4f0c-b6bc-75a082a2167b)
还有一个新的问题，就是经常会这样左边自己队友不显示选的英雄，对面的可以显示，切换到其他界面再切回来也是不显示，点左下角的那个重新加载也是不显示，旧版不会这样

**Comment by Hpero4** [comment]
@kissgo 方便提供一下log吗? 实在是不太好复现这几种情况, 偶尔收到反馈也都比较零散🥲

**Comment by kissgo** [comment]
> @kissgo 方便提供一下log吗? 实在是不太好复现这几种情况, 偶尔收到反馈也都比较零散🥲

[Seraphine_2024-05-10_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/15308660/Seraphine_2024-05-10_ERROR.log)
[Seraphine_2024-05-11_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/15308661/Seraphine_2024-05-11_ERROR.log)
[Seraphine_2024-05-12_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/15308662/Seraphine_2024-05-12_ERROR.log)
[Seraphine_2024-05-13_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/15308665/Seraphine_2024-05-13_ERROR.log)
[Seraphine_2024-05-14_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/15308666/Seraphine_2024-05-14_ERROR.log)

好的，这是我重装之后这五天的log,辛苦了😢

**Comment by fray8023** [comment]
我遇到了另外一个报错问题
复现过程：在软件不关闭的时候，关闭打开lol客户端


Seraphine ver.1.0.0
-----
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 471, in __onLolClientStarted
  File "app\view\main_window.py", line 535, in __startConnector
  File "app\lol\connector.py", line 241, in start
  File "app\lol\connector.py", line 315, in __initSessions
  File "app\lol\connector.py", line 116, in wrapper
  File "app\lol\connector.py", line 88, in wrapper
  File "app\lol\connector.py", line 1014, in getSGPtoken
ReferenceError

**Comment by xiaomingzzzzz** [comment]
插个楼 偶尔我在国服和日服切换的时候软件会报bug退出 下次遇到我再来贴图
