### ISSUE TITLE
我也不知道是算什么 只是偶尔打完游戏 或者刚开软件的时候会报出这个 然后只能关闭重开

### ISSUE THREAD

**Issue by 2608686003** [Zzaphkiel/Seraphine#391]
### 问题描述

Traceback (most recent call last):
  File "app\view\main_window.py", line 451, in __startConnector
  File "app\lol\connector.py", line 175, in start
  File "app\lol\connector.py", line 234, in __initManager
  File "app\lol\connector.py", line 277, in __json_retry_get
app.lol.exceptions.RetryMaximumAttempts: Exceeded maximum retry attempts.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 424, in __onLolClientStarted
  File "app\view\main_window.py", line 456, in __startConnector
  File "app\lol\connector.py", line 209, in close
RuntimeError: super-class __init__() of type LolClientConnector was never called

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.11.1

### 客户端状态（若有）

首页

### 出现率（若有）

差不多一半的情况会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
换新版本。

**Comment by 2608686003** [comment]
不好意思 我才发现有更新  我刚刚完成了更新 打完一局游戏之后 现在又出现了这个
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 726, in __onGameStatusChanged
  File "app\view\main_window.py", line 841, in __onGameStart
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 733, in __onGameStatusChanged
  File "app\view\main_window.py", line 841, in __onGameStart
TypeError: 'NoneType' object is not subscriptable

**Comment by Zzaphkiel** [comment]
暂时不知道什么原因，可以尝试：
1. 将客户端设置中 “在游戏时关闭关闭客户端” 改为 “从不”。
2. 关闭 Seraphine 的 “自动重新连接” 功能。。
