### ISSUE TITLE
[BUG] 更新后无法使用。

### ISSUE THREAD

**Issue by RikkaLzw** [Zzaphkiel/Seraphine#401]
### 问题描述

自动更新后被360拦截后，不管是github还是群文件下载都无法使用。
360拦截记录：
（1）时间	操作	说明	次数
2024-06-16 14:04:43	[自动阻止]	  修改 关键程序DLL文件	防护 1 次
详细描述：
进程：C:\Users\33519\Desktop\Seraphine\Seraphine.exe
动作：试图修改
路径：C:\Users\33519\AppData\Roaming\Seraphine\temp\PyQt5\Qt5\bin\d3dcompiler_47.dll 
不再提醒(0x666e807b)
防护信息: FD|18, 548|30, 30, -1|||

报错场景：游戏客户端未打开不会报错，打开了转圈刷新就会出现。

重新解压、重启电脑、关闭杀毒软件均无用

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

13.0

### 客户端状态（若有）

挂着

### 日志文件

报错显示：
Seraphine ver.0.13.1-beta1
-----
Traceback (most recent call last):
  File "requests\models.py", line 974, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 485, in __onLolClientStarted
  File "app\lol\aram.py", line 43, in checkAndUpdate
  File "app\lol\aram.py", line 112, in __update
  File "requests\models.py", line 978, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### 您进行游戏的服务器（若有）

钢铁烈阳

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by RikkaLzw** [comment]
问题发生在__onLolClientStarted方法中调用checkAndUpdate方法，而checkAndUpdate方法又调用了__update方法。在__update方法中，requests库的json方法抛出了异常。你可以在这些方法中添加调试信息，进一步确定问题的具体位置和原因。

**Comment by Zzaphkiel** [comment]
猜测是你的杀毒软件把什么东西干掉了，导致获取大乱斗 buff 信息时使用的 `requests.get()` 得到了空的内容。

可能的解决方法：
- 手动获取大乱斗 BUFF 信息（参考代码报错部分给出的 HTTP 请求参数），命名为 `AramBuff.json` 并放在 `%APPDATA%\Seraphine` 目录下；
- 或查看杀毒软件查杀历史，恢复被删除的文件；
- 或重装系统。
