### ISSUE TITLE
[BUG] 点击最近队友之后通过战绩查询页面再查看他人生涯会导致异常崩溃

### ISSUE THREAD

**Issue by asd2422313947** [Zzaphkiel/Seraphine#403]
### 问题描述

Seraphine ver.0.13.1-beta1
-----
Traceback (most recent call last):
  File "C:\hj\lib\site-packages\qasync\__init__.py", line 780, in _error_handler
    task.result()
  File "C:\Seraphine-main\app\view\main_window.py", line 711, in __switchToCareerInterface
    await self.careerInterface.updateInterface(puuid=puuid)
  File "C:\Seraphine-main\app\view\career_interface.py", line 388, in updateInterface
    self.recentTeammatesFlyout.close()
RuntimeError: wrapped C/C++ object of type Flyout has been deleted

### 系统信息

Windows 10

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

最新源代码

### 复现方法（若有）

点击一次“最近队友”，再使用“战绩查询”，然后点击任意”战绩查询“中的任意玩家战绩，在跳转到生涯界面时，触发异常崩溃。

### 日志文件

已连接到 pydev 调试器(内部版本号 241.14494.241)Traceback (most recent call last):
  File "C:\hj\lib\site-packages\qasync\__init__.py", line 780, in _error_handler
    task.result()
  File "C:\Seraphine-main\app\view\main_window.py", line 711, in __switchToCareerInterface
    await self.careerInterface.updateInterface(puuid=puuid)
  File "C:\Seraphine-main\app\view\career_interface.py", line 388, in updateInterface
    self.recentTeammatesFlyout.close()
RuntimeError: wrapped C/C++ object of type Flyout has been deleted

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by asd2422313947** [comment]
根据测试：点击最近队友之后，如果查看了最近队友的生涯，则一切正常不会触发异常崩溃，如果只是点击最近队友，不进入对应队友的生涯，这时再去查看任意玩家的生涯，就会触发异常崩溃

**Comment by asd2422313947** [comment]
还有另外一个也是由最近队友触发的异常，就是刚打开软件，生涯界面转圈完毕刚加载好，迅速点击最近队友，也会导致异常崩溃：
已连接到 pydev 调试器(内部版本号 241.14494.241)Traceback (most recent call last):
  File "C:\Seraphine-main\app\view\career_interface.py", line 568, in __onRecentTeammatesButtonClicked
    if self.info:
AttributeError: 'CareerInterface' object has no attribute 'info'

**Comment by asd2422313947** [comment]
经过检查是这个修复导致了此问题https://github.com/Zzaphkiel/Seraphine/commit/95dec938680401b435937e8e303485a787366862

**Comment by Zzaphkiel** [comment]
等我不忙了试一下，最近事情有点多

**Comment by Zzaphkiel** [comment]
已修复该问题
