### ISSUE TITLE
启动崩溃

### ISSUE THREAD

**Issue by xiaojie-alt** [Zzaphkiel/Seraphine#405]
### 问题描述

Seraphine ver.0.13.0
-----
Traceback (most recent call last):
  File "psutil\_pswindows.py", line 834, in cmdline
PermissionError: [WinError 5] 拒绝访问。: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "psutil\_pswindows.py", line 730, in wrapper
  File "psutil\_pswindows.py", line 748, in wrapper
  File "psutil\_pswindows.py", line 837, in cmdline
PermissionError: [WinError 5] 拒绝访问。: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 432, in __onLolClientStarted
  File "app\view\main_window.py", line 492, in __startConnector
  File "app\lol\connector.py", line 218, in start
  File "app\common\util.py", line 195, in getPortTokenServerByPid
  File "psutil\__init__.py", line 719, in cmdline
  File "psutil\_pswindows.py", line 732, in wrapper
psutil.AccessDenied: (pid=18884)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.13.0

### 客户端状态（若有）

无论什么状态

### 复现方法（若有）

只要双击启动客户端必然复现

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
#358

**Comment by Zzaphkiel** [comment]
如果方便的话可以尝试一下：启动 LOL 客户端进入大厅，使用管理员身份打开 cmd，运行命令 
``` shell
wmic process WHERE name='LeagueClientUx.exe' GET commandline
```
能正确获取到启动参数吗？

**Comment by kksama2020** [comment]
我也遇到这个问题了，启动就崩溃

**Comment by kksama2020** [comment]
能获取到启动参数
