### ISSUE TITLE
[BUG] 进入就报错退出

### ISSUE THREAD

**Issue by Shon-Sion** [Zzaphkiel/Seraphine#413]
### 问题描述

程序进入就报错退出，错误代码
Seraphine ver.0.13.0
-----
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 487, in __onLolClientStarted
  File "app\lol\aram.py", line 42, in checkAndUpdate
  File "app\lol\aram.py", line 143, in __checkUpdate
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
![image](https://github.com/Zzaphkiel/Seraphine/assets/174631433/53e02647-ee2e-45ae-9375-a4178e91c791)

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.13.0

### 客户端状态（若有）

任何状态打开都会出现

### 日志文件

Seraphine ver.0.13.0
-----
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 487, in __onLolClientStarted
  File "app\lol\aram.py", line 42, in checkAndUpdate
  File "app\lol\aram.py", line 143, in __checkUpdate
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
https://github.com/Zzaphkiel/Seraphine/issues/412#issuecomment-2198463788

**Comment by Shon-Sion** [comment]
没有该文件
![image](https://github.com/Zzaphkiel/Seraphine/assets/174631433/809da457-3456-4d8c-82ed-49a659a619ae)
![image](https://github.com/Zzaphkiel/Seraphine/assets/174631433/ae8d38e9-aa60-4f5a-ae39-04fc3331e9b8)

**Comment by Zzaphkiel** [comment]
你找错地方了，应按 `win + r` 打开 “运行”，输入 `%AppData%\Seraphine` 后回车就能看到了。
