### ISSUE TITLE
[BUG] 查看斗魂竞技场战绩会报错

### ISSUE THREAD

**Issue by yeslinyh** [Zzaphkiel/Seraphine#417]
### 问题描述

打开 `斗魂竞技场` 战绩后，**闪退**

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.13.1

### 客户端状态（若有）

房间组队中

### 复现方法（若有）

![](https://img.pcdiy.xyz/file/5da03324564bdfac44578.png)

### 日志文件

````
Seraphine ver.0.13.1
-----
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 942, in __onCareerGameClicked
  File "app\view\search_interface.py", line 1288, in updateGameDetailView
  File "app\lol\tools.py", line 383, in parseGameDetailData
KeyError: 0
````

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
无法复现该问题

**Comment by Zzaphkiel** [comment]
> 无法复现该问题，但我的对局是六月一号的，可能最近改了返回的数据内容所以报错了

找了今天的对局战绩依旧无法复现 😰
