### ISSUE TITLE
[BUG] 自动接受交换请求不起作用

### ISSUE THREAD

**Issue by CHANTY713** [Zzaphkiel/Seraphine#436]
### 问题描述

已开启自动接收楼层交换请求，关闭英雄交换请求，游戏内交换请求并未自动接受
其他自动功能正常

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

v1.0.0

### 客户端状态（若有）

英雄选择

### 复现方法（若有）

队友提起交换楼层请求

### 日志文件

Traceback (most recent call last):
  File "app\lol\connector.py", line 88, in wrapper
  File "app\lol\connector.py", line 1010, in getSGPtoken
  File "app\lol\connector.py", line 47, in wrapper
  File "app\lol\connector.py", line 1067, in __get
  File "aiohttp\client.py", line 581, in _request
  File "aiohttp\connector.py", line 544, in connect
  File "aiohttp\connector.py", line 944, in _create_connection
  File "aiohttp\connector.py", line 1257, in _create_direct_connection
  File "aiohttp\connector.py", line 1226, in _create_direct_connection
  File "aiohttp\connector.py", line 1033, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:62480 ssl:False [远程计算机拒绝网络连接。]

2024-08-04 13:22:43,854 - [MainWindow] CRITICAL - League of Legends client ended
2024-08-04 13:24:03,561 - [MainWindow] CRITICAL - Seraphine started, version: 1.0.0
2024-08-04 13:24:05,293 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-08-04 13:24:05,294 - [MainWindow] CRITICAL - Seraphine listerners started
2024-08-04 13:24:05,592 - [MainWindow] CRITICAL - Seraphine initialized
2024-08-04 13:25:27,376 - [Connector] CRITICAL - connector started, server: HN1
2024-08-04 13:31:54,351 - [Connector] ERROR - getItemIconPath, iconId: 7004
2024-08-04 13:32:02,614 - [Connector] ERROR - getItemIconPath, iconId: 7029
2024-08-04 13:33:26,359 - [Connector] ERROR - getItemIconPath, iconId: 7002
2024-08-04 13:33:26,375 - [Connector] ERROR - getItemIconPath, iconId: 7010
2024-08-04 13:33:28,192 - [Connector] ERROR - getItemIconPath, iconId: 7020
2024-08-04 14:07:52,112 - [Connector] ERROR - getItemIconPath, iconId: 2419
2024-08-04 14:59:40,804 - [MainWindow] CRITICAL - League of Legends client changed: 12896
2024-08-04 14:59:40,805 - [MainWindow] CRITICAL - League of Legends client ended
2024-08-04 14:59:41,187 - [Connector] CRITICAL - connector started, server: HN1
2024-08-04 15:01:55,856 - [MainWindow] CRITICAL - League of Legends client changed: 5256
2024-08-04 15:01:55,857 - [MainWindow] CRITICAL - League of Legends client ended
2024-08-04 15:01:56,136 - [Connector] CRITICAL - connector started, server: HN1
2024-08-04 15:57:17,069 - [MainWindow] CRITICAL - League of Legends client ended
2024-08-04 15:58:37,622 - [Connector] CRITICAL - connector started, server: HN1
2024-08-04 16:04:00,435 - [MainWindow] CRITICAL - League of Legends client changed: 8884
2024-08-04 16:04:00,435 - [MainWindow] CRITICAL - League of Legends client ended
2024-08-04 16:04:00,853 - [Connector] CRITICAL - connector started, server: HN1
2024-08-04 17:20:42,342 - [Connector] ERROR - getItemIconPath, iconId: 7034
2024-08-04 17:22:12,421 - [Connector] ERROR - getItemIconPath, iconId: 7003
2024-08-04 17:22:29,008 - [Connector] ERROR - getItemIconPath, iconId: 7007
2024-08-04 17:22:54,280 - [Connector] ERROR - getItemIconPath, iconId: 7008
2024-08-04 18:12:36,582 - [Connector] ERROR - getItemIconPath, iconId: 7042

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
旧版本有这个问题吗？

**Comment by CHANTY713** [comment]
没用过旧版本


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月5日(周一) 下午3:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zzaphkiel/Seraphine] [BUG] 自动接受交换请求不起作用 (Issue #436)




 
旧版本有这个问题吗？
 
&mdash;

**Comment by Zzaphkiel** [comment]
接受自动交换是有一秒钟延迟的，是一秒之后依旧没有自动接受吗？

**Comment by CHANTY713** [comment]
时间结束了也没有接受，也没有把seraphine放在后台


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月5日(周一) 下午3:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zzaphkiel/Seraphine] [BUG] 自动接受交换请求不起作用 (Issue #436)




 
接受自动交换是有一秒钟延迟的，是一秒之后依旧没有自动接受吗？
 
&mdash;

**Comment by Zzaphkiel** [comment]
该问题和 #435 类似，请移步 #435 了解进展。
