### ISSUE TITLE
崩溃了

### ISSUE THREAD

**Issue by l90881** [Zzaphkiel/Seraphine#465]
### 问题描述

以下是崩溃代码

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.0

### 日志文件

Seraphine ver.1.0.0
-----
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
RuntimeError: cannot reuse already awaited coroutine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
RuntimeError: cannot reuse already awaited coroutine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
RuntimeError: cannot reuse already awaited coroutine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
RuntimeError: cannot reuse already awaited coroutine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
RuntimeError: cannot reuse already awaited coroutine

### 出现率（若有）

只有第一次出现了，之后再没遇见过

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
不知道第一次怎么崩溃 + 不知道之后如何复现 = 修复难度大 + 修复意义小
