### ISSUE TITLE
[Question] 在IDE里面一调试模式启动就报错，直接运行却不会

### ISSUE THREAD

**Issue by Ninohana** [Zzaphkiel/Seraphine#470]
### 问题描述

以前也不会，不知道是IDE的问题，还是仓库代码的问题，大伙有什么头猪吗？🤔

界面一闪而过，紧接着就报错。

日志：

```
D:\anaconda3\envs\seraphine\python.exe -X pycache_prefix=C:\Users\ninoh\AppData\Local\JetBrains\PyCharm2024.2\cpython-cache "D:/JetBrains/PyCharm 2024.1/plugins/python-ce/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 58979 --file C:\Users\ninoh\Project\Seraphine\main.py 
已连接到 pydev 调试器(内部版本号 242.21829.153)
Traceback (most recent call last):
  File "D:/JetBrains/PyCharm 2024.1/plugins/python-ce/helpers/pydev/pydevd.py", line 1557, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\JetBrains\PyCharm 2024.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\ninoh\Project\Seraphine\main.py", line 61, in <module>
    main()
  File "C:\Users\ninoh\Project\Seraphine\main.py", line 56, in main
    eventLoop.run_until_complete(appCloseEvent.wait())
  File "D:\anaconda3\envs\seraphine\lib\site-packages\qasync\__init__.py", line 394, in run_until_complete
    future = asyncio.ensure_future(future, loop=self)
  File "D:\JetBrains\PyCharm 2024.1\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 174, in ensure_future
    return loop.create_task(coro_or_future)
  File "D:\anaconda3\envs\seraphine\lib\asyncio\base_events.py", line 431, in create_task
    task = tasks.Task(coro, loop=self, name=name)
  File "D:\JetBrains\PyCharm 2024.1\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 424, in task_new_init
    self._loop.call_soon(self, context=self._context)
  File "D:\anaconda3\envs\seraphine\lib\site-packages\qasync\__init__.py", line 481, in call_soon
    return self.call_later(0, callback, *args, context=context)
  File "D:\anaconda3\envs\seraphine\lib\site-packages\qasync\__init__.py", line 459, in call_later
    raise TypeError(
TypeError: callback must be callable: Task

进程已结束，退出代码为 -1073740791 (0xC0000409)
```

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by maplelost** [comment]
https://youtrack.jetbrains.com/issue/PY-62467/TypeError-Task-object-is-not-callable-debugging-uvloop-with-asyncio-support-enabled#focus=Comments-27-9543178.0-0

This answer work for me.
