### ISSUE TITLE
[BUG] （启动软件无法进入界面，只出现居中的萨勒芬妮图标）

### ISSUE THREAD

**Issue by atychiphobiaa** [Zzaphkiel/Seraphine#477]
### 问题描述

**在使用Windows11 24H2版本时出现的问题，23H2没问题**，启动软件没进入界面，只是出现居中的萨勒芬妮图标。窗口可以关闭，任务栏退出无反应；管理器中找不到进程，可以重复打开多个软件，但是任务栏图标仍然无法退出。重装软件和重启电脑都无法解决，但是切换到另一个23H2的系统可以正常使用（双系统）；截图和Log附上了。
![2024-09-30_152256](https://github.com/user-attachments/assets/27358faa-7bbe-46e0-bdfd-f6f56ce44006)

![2024-09-30_152733](https://github.com/user-attachments/assets/160677a6-0111-4c77-84f0-676361002038)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

v1.0.0

### 日志文件

2024-09-30 15:18:44,744 - [MainWindow] CRITICAL - Seraphine started, version: 1.0.0
2024-09-30 15:18:45,400 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-09-30 15:18:45,400 - [MainWindow] CRITICAL - Seraphine listerners started
2024-09-30 15:18:45,680 - [Crash] ERROR - Exception occurred:
Traceback (most recent call last):
  File "main.py", line 61, in <module>
  File "main.py", line 53, in main
  File "app\view\main_window.py", line 108, in __init__
  File "app\view\main_window.py", line 653, in __autoStartLolClient
  File "app\view\main_window.py", line 657, in __startLolClient
IndexError: list index out of range

2024-09-30 15:18:45,680 - [Crash] ERROR - SearchInterface(puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0)
2024-09-30 15:18:45,680 - [Crash] ERROR - GameInfoInterface(isAram(bool)=False, allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0)
2024-09-30 15:18:45,680 - [Crash] ERROR - CareerInterface(currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, recentTeammatesInfo(NoneType)=None, rankInfo(list)=[['单 / 双排'], ['灵活排位']], recentTeammatesFlyout(NoneType)=None, games(list)=[], loadGamesTask(NoneType)=None)
2024-09-30 15:18:45,680 - [Crash] ERROR - AuxiliaryInterface()
2024-09-30 15:18:45,680 - [Crash] ERROR - SettingInterface()
2024-09-30 15:27:05,850 - [MainWindow] CRITICAL - Seraphine started, version: 1.0.0
2024-09-30 15:27:06,444 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-09-30 15:27:06,444 - [MainWindow] CRITICAL - Seraphine listerners started
2024-09-30 15:27:06,769 - [Crash] ERROR - Exception occurred:
Traceback (most recent call last):
  File "main.py", line 61, in <module>
  File "main.py", line 53, in main
  File "app\view\main_window.py", line 108, in __init__
  File "app\view\main_window.py", line 653, in __autoStartLolClient
  File "app\view\main_window.py", line 657, in __startLolClient
IndexError: list index out of range

2024-09-30 15:27:06,769 - [Crash] ERROR - SearchInterface(puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0)
2024-09-30 15:27:06,769 - [Crash] ERROR - GameInfoInterface(isAram(bool)=False, allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0)
2024-09-30 15:27:06,770 - [Crash] ERROR - CareerInterface(currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, recentTeammatesInfo(NoneType)=None, rankInfo(list)=[['单 / 双排'], ['灵活排位']], recentTeammatesFlyout(NoneType)=None, games(list)=[], loadGamesTask(NoneType)=None)
2024-09-30 15:27:06,770 - [Crash] ERROR - AuxiliaryInterface()
2024-09-30 15:27:06,770 - [Crash] ERROR - SettingInterface()
2024-09-30 15:27:08,384 - [MainWindow] CRITICAL - Seraphine started, version: 1.0.0
2024-09-30 15:27:08,957 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-09-30 15:27:08,958 - [MainWindow] CRITICAL - Seraphine listerners started
2024-09-30 15:27:09,240 - [Crash] ERROR - Exception occurred:
Traceback (most recent call last):
  File "main.py", line 61, in <module>
  File "main.py", line 53, in main
  File "app\view\main_window.py", line 108, in __init__
  File "app\view\main_window.py", line 653, in __autoStartLolClient
  File "app\view\main_window.py", line 657, in __startLolClient
IndexError: list index out of range

2024-09-30 15:27:09,240 - [Crash] ERROR - SearchInterface(puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0)
2024-09-30 15:27:09,241 - [Crash] ERROR - GameInfoInterface(isAram(bool)=False, allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0)
2024-09-30 15:27:09,241 - [Crash] ERROR - CareerInterface(currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, recentTeammatesInfo(NoneType)=None, rankInfo(list)=[['单 / 双排'], ['灵活排位']], recentTeammatesFlyout(NoneType)=None, games(list)=[], loadGamesTask(NoneType)=None)
2024-09-30 15:27:09,241 - [Crash] ERROR - AuxiliaryInterface()
2024-09-30 15:27:09,242 - [Crash] ERROR - SettingInterface()

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
没法测试，暂时修不了 🥲

**Comment by atychiphobiaa** [comment]
嘿嘿😁我发现解决办法了:在切换系统之后，先自行启动leagueclient再启动seraphine即可正常运行
