### ISSUE TITLE
[BUG] 程序运行报错

### ISSUE THREAD

**Issue by 6get-xiaofan** [Zzaphkiel/Seraphine#500]
### 问题描述

客户端运行打开程序后报错：

```txt
Seraphine ver.1.0.0
-----
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 471, in __onLolClientStarted
  File "app\view\main_window.py", line 535, in __startConnector
  File "app\lol\connector.py", line 244, in start
  File "app\lol\connector.py", line 319, in __initFolder
PermissionError: [WinError 5] Access is denied: 'app/resource/game'

```

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.0

### 客户端状态（若有）

刚运行

### 日志文件

```
2024-10-24 10:06:22,419 - [MainWindow] CRITICAL - Seraphine started, version: 1.0.0
2024-10-24 10:06:23,785 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-10-24 10:06:23,786 - [MainWindow] CRITICAL - Seraphine listerners started
2024-10-24 10:06:24,265 - [MainWindow] CRITICAL - Seraphine initialized
2024-10-24 10:08:52,804 - [Crash] ERROR - Exception occurred:
Traceback (most recent call last):
  File "qfluentwidgets\components\widgets\info_bar.py", line 420, in eventFilter
RuntimeError: wrapped C/C++ object of type BottomRightInfoBarManager has been deleted

2024-10-24 10:08:52,804 - [Crash] ERROR - SearchInterface(puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0)
2024-10-24 10:08:52,805 - [Crash] ERROR - GameInfoInterface(isAram(bool)=False, allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0)
2024-10-24 10:08:52,805 - [Crash] ERROR - CareerInterface(currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, recentTeammatesInfo(NoneType)=None, rankInfo(list)=[['Ranked Solo'], ['Ranked Flex']], recentTeammatesFlyout(NoneType)=None, games(list)=[], loadGamesTask(NoneType)=None)
2024-10-24 10:08:52,805 - [Crash] ERROR - AuxiliaryInterface()
2024-10-24 10:08:52,806 - [Crash] ERROR - SettingInterface()
2024-10-24 10:08:56,962 - [MainWindow] CRITICAL - Seraphine started, version: 1.0.0
2024-10-24 10:08:57,945 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-10-24 10:08:57,945 - [MainWindow] CRITICAL - Seraphine listerners started
2024-10-24 10:08:58,493 - [MainWindow] CRITICAL - Seraphine initialized
2024-10-24 10:17:43,490 - [Connector] ERROR - exit getSGPtoken: Traceback (most recent call last):
  File "aiohttp\connector.py", line 1025, in _wrap_create_connection
  File "asyncio\base_events.py", line 1025, in create_connection
  File "asyncio\base_events.py", line 1010, in create_connection
  File "asyncio\base_events.py", line 924, in _connect_sock
  File "asyncio\proactor_events.py", line 702, in sock_connect
  File "qasync\_windows.py", line 43, in _process_events
  File "asyncio\windows_events.py", line 599, in finish_connect
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app\lol\connector.py", line 88, in wrapper
  File "app\lol\connector.py", line 1010, in getSGPtoken
  File "app\lol\connector.py", line 47, in wrapper
  File "app\lol\connector.py", line 1067, in __get
  File "aiohttp\client.py", line 581, in _request
  File "aiohttp\connector.py", line 544, in connect
  File "aiohttp\connector.py", line 944, in _create_connection
  File "aiohttp\connector.py", line 1257, in _create_direct_connection
  File "aiohttp\connector.py", line 1226, in _create_direct_connection
  File "aiohttp\connector.py", line 1033, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:8550 ssl:False [The remote computer refused the network connection]

2024-10-24 10:19:02,392 - [MainWindow] CRITICAL - League of Legends client ended
2024-10-24 17:30:44,081 - [MainWindow] CRITICAL - Seraphine started, version: 1.0.0
2024-10-24 17:30:45,298 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-10-24 17:30:45,299 - [MainWindow] CRITICAL - Seraphine listerners started
2024-10-24 17:30:45,765 - [MainWindow] CRITICAL - Seraphine initialized
2024-10-24 18:23:57,063 - [MainWindow] CRITICAL - Seraphine started, version: 1.0.0
2024-10-24 18:23:58,303 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-10-24 18:23:58,303 - [MainWindow] CRITICAL - Seraphine listerners started
2024-10-24 18:23:58,822 - [MainWindow] CRITICAL - Seraphine initialized
2024-10-24 18:25:32,276 - [Crash] ERROR - Exception occurred:
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 471, in __onLolClientStarted
  File "app\view\main_window.py", line 535, in __startConnector
  File "app\lol\connector.py", line 244, in start
  File "app\lol\connector.py", line 319, in __initFolder
PermissionError: [WinError 5] Access is denied: 'app/resource/game'

2024-10-24 18:25:32,276 - [Crash] ERROR - PastRequest(func='getSGPtoken', params_dict={}, kwargs={}, response='eyJraWQiOiJvbmNVIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIzNWEzZjIxMS1jY2ZkLTVhOGItYTQ1MS1iOTdlODkxMmVhYzciLCJzY3AiOlsib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiLCJsb2wiLCJiYW4iLCJwcm9maWxlIiwiZW1haWwiLCJwaG9uZSJdLCJjbG0iOlsic3ViIiwiem9uZWluZm8iLCJiaXJ0aGRhdGUiLCJyZ25faG4xMCIsImdlbmRlciIsInB3IiwibG9sIiwicHJlZmVycmVkX3VzZXJuYW1lIiwibG9jYWxlIiwiYmFuIiwidXBkYXRlZF9hdCIsIm5pY2tuYW1lIiwic3VtbW9uZXIiLCJhY2N0X2dudCIsImVtYWlsIiwid2Vic2l0ZSIsImVtYWlsX3ZlcmlmaWVkIiwib3BlbmlkIiwicHJvZmlsZSIsInBob25lX251bWJlcl92ZXJpZmllZCIsImdpdmVuX25hbWUiLCJtaWRkbGVfbmFtZSIsInBpY3R1cmUiLCJuYW1lIiwicGhvbmVfbnVtYmVyIiwiZmFtaWx5X25hbWUiLCJhY2N0IiwidXNlcm5hbWUiXSwiZGF0Ijp7InAiOiIxNzIzMzI3OTMyIiwiciI6IkhOMTAiLCJjIjoiY3FjbG91ZCIsInUiOjE3MDA0NjI1MTk5fSwiaXNzIjoiaHR0cHM6Ly9sb2wucXEuY29tIiwicGx0Ijp7ImRldiI6InVua25vd24iLCJpZCI6InVua25vd24ifSwiZXhwIjoxNzI5NzY2MTE1LCJpYXQiOjE3Mjk3NjU1MTUsImp0aSI6Il9MTXR0Y29vY1JvIiwiY2lkIjoibG9sIn0.WPiGLEWgxX-n2O6pmZu1Sg_aNJ-LBuZ0OM0DhW1L-4iHKwn5BxljeeMpWWKH33_9aOu5MLXFDpWdeRKWt3eatthoT7ynNPBzKFMjsoVPxxZQXN5qfF04bc_f4ObTBOpK3oaLdkCG9RpEuiKup3LOQVk_yJEvd4OGUMavMbv0j8hVjFalcg7xKEZt8thHuhMJLC3EZ3E_YfzFD2LYjGpy5j9XOmHljx2sRdLle2IRIhD6Kdq50Yd2wKe6UEf1hLFO6I_5dUNewcqFI-PwMnouagd_fyByCSyPpQ9O4vIcv6NwntrHH-NxZDs1WUbNIzqcIi103zfYV7jHJBwjG1XpfQ', timestamp=1729765532.1901443)
2024-10-24 18:25:32,276 - [Crash] ERROR - SearchInterface(puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0)
2024-10-24 18:25:32,277 - [Crash] ERROR - GameInfoInterface(isAram(bool)=False, allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0)
2024-10-24 18:25:32,277 - [Crash] ERROR - CareerInterface(currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, recentTeammatesInfo(NoneType)=None, rankInfo(list)=[['单 / 双排'], ['灵活排位']], recentTeammatesFlyout(NoneType)=None, games(list)=[], loadGamesTask(NoneType)=None)
2024-10-24 18:25:32,278 - [Crash] ERROR - AuxiliaryInterface()
2024-10-24 18:25:32,278 - [Crash] ERROR - SettingInterface()
2024-10-24 18:30:24,896 - [Crash] ERROR - Abnormal exit
2024-10-24 18:31:32,572 - [MainWindow] CRITICAL - Seraphine started, version: 1.0.0
2024-10-24 18:31:33,868 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-10-24 18:31:33,869 - [MainWindow] CRITICAL - Seraphine listerners started
2024-10-24 18:31:34,374 - [MainWindow] CRITICAL - Seraphine initialized
2024-10-24 18:31:34,817 - [Crash] ERROR - Exception occurred:
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 471, in __onLolClientStarted
  File "app\view\main_window.py", line 535, in __startConnector
  File "app\lol\connector.py", line 244, in start
  File "app\lol\connector.py", line 319, in __initFolder
PermissionError: [WinError 5] Access is denied: 'app/resource/game'

2024-10-24 18:31:34,818 - [Crash] ERROR - PastRequest(func='getSGPtoken', params_dict={}, kwargs={}, response='eyJraWQiOiJvbmNVIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIzNWEzZjIxMS1jY2ZkLTVhOGItYTQ1MS1iOTdlODkxMmVhYzciLCJzY3AiOlsib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiLCJsb2wiLCJiYW4iLCJwcm9maWxlIiwiZW1haWwiLCJwaG9uZSJdLCJjbG0iOlsic3ViIiwiem9uZWluZm8iLCJiaXJ0aGRhdGUiLCJyZ25faG4xMCIsImdlbmRlciIsInB3IiwibG9sIiwicHJlZmVycmVkX3VzZXJuYW1lIiwibG9jYWxlIiwiYmFuIiwidXBkYXRlZF9hdCIsIm5pY2tuYW1lIiwic3VtbW9uZXIiLCJhY2N0X2dudCIsImVtYWlsIiwid2Vic2l0ZSIsImVtYWlsX3ZlcmlmaWVkIiwib3BlbmlkIiwicHJvZmlsZSIsInBob25lX251bWJlcl92ZXJpZmllZCIsImdpdmVuX25hbWUiLCJtaWRkbGVfbmFtZSIsInBpY3R1cmUiLCJuYW1lIiwicGhvbmVfbnVtYmVyIiwiZmFtaWx5X25hbWUiLCJhY2N0IiwidXNlcm5hbWUiXSwiZGF0Ijp7InAiOiIxNzIzMzI3OTMyIiwiciI6IkhOMTAiLCJjIjoiY3FjbG91ZCIsInUiOjE3MDA0NjI1MTk5fSwiaXNzIjoiaHR0cHM6Ly9sb2wucXEuY29tIiwicGx0Ijp7ImRldiI6InVua25vd24iLCJpZCI6InVua25vd24ifSwiZXhwIjoxNzI5NzY2MTE1LCJpYXQiOjE3Mjk3NjU1MTUsImp0aSI6Il9MTXR0Y29vY1JvIiwiY2lkIjoibG9sIn0.WPiGLEWgxX-n2O6pmZu1Sg_aNJ-LBuZ0OM0DhW1L-4iHKwn5BxljeeMpWWKH33_9aOu5MLXFDpWdeRKWt3eatthoT7ynNPBzKFMjsoVPxxZQXN5qfF04bc_f4ObTBOpK3oaLdkCG9RpEuiKup3LOQVk_yJEvd4OGUMavMbv0j8hVjFalcg7xKEZt8thHuhMJLC3EZ3E_YfzFD2LYjGpy5j9XOmHljx2sRdLle2IRIhD6Kdq50Yd2wKe6UEf1hLFO6I_5dUNewcqFI-PwMnouagd_fyByCSyPpQ9O4vIcv6NwntrHH-NxZDs1WUbNIzqcIi103zfYV7jHJBwjG1XpfQ', timestamp=1729765894.726811)
2024-10-24 18:31:34,818 - [Crash] ERROR - SearchInterface(puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0)
2024-10-24 18:31:34,819 - [Crash] ERROR - GameInfoInterface(isAram(bool)=False, allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0)
2024-10-24 18:31:34,819 - [Crash] ERROR - CareerInterface(currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, recentTeammatesInfo(NoneType)=None, rankInfo(list)=[['单 / 双排'], ['灵活排位']], recentTeammatesFlyout(NoneType)=None, games(list)=[], loadGamesTask(NoneType)=None)
2024-10-24 18:31:34,819 - [Crash] ERROR - AuxiliaryInterface()
2024-10-24 18:31:34,819 - [Crash] ERROR - SettingInterface()
2024-10-24 18:31:46,400 - [Crash] ERROR - Abnormal exit
2024-10-24 18:33:36,149 - [MainWindow] CRITICAL - Seraphine started, version: 1.0.0
2024-10-24 18:33:37,237 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-10-24 18:33:37,237 - [MainWindow] CRITICAL - Seraphine listerners started
2024-10-24 18:33:37,746 - [MainWindow] CRITICAL - Seraphine initialized
2024-10-24 18:33:38,263 - [Crash] ERROR - Exception occurred:
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 471, in __onLolClientStarted
  File "app\view\main_window.py", line 535, in __startConnector
  File "app\lol\connector.py", line 244, in start
  File "app\lol\connector.py", line 319, in __initFolder
PermissionError: [WinError 5] Access is denied: 'app/resource/game'

2024-10-24 18:33:38,263 - [Crash] ERROR - PastRequest(func='getSGPtoken', params_dict={}, kwargs={}, response='eyJraWQiOiJvbmNVIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIzNWEzZjIxMS1jY2ZkLTVhOGItYTQ1MS1iOTdlODkxMmVhYzciLCJzY3AiOlsib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiLCJsb2wiLCJiYW4iLCJwcm9maWxlIiwiZW1haWwiLCJwaG9uZSJdLCJjbG0iOlsic3ViIiwiem9uZWluZm8iLCJiaXJ0aGRhdGUiLCJyZ25faG4xMCIsImdlbmRlciIsInB3IiwibG9sIiwicHJlZmVycmVkX3VzZXJuYW1lIiwibG9jYWxlIiwiYmFuIiwidXBkYXRlZF9hdCIsIm5pY2tuYW1lIiwic3VtbW9uZXIiLCJhY2N0X2dudCIsImVtYWlsIiwid2Vic2l0ZSIsImVtYWlsX3ZlcmlmaWVkIiwib3BlbmlkIiwicHJvZmlsZSIsInBob25lX251bWJlcl92ZXJpZmllZCIsImdpdmVuX25hbWUiLCJtaWRkbGVfbmFtZSIsInBpY3R1cmUiLCJuYW1lIiwicGhvbmVfbnVtYmVyIiwiZmFtaWx5X25hbWUiLCJhY2N0IiwidXNlcm5hbWUiXSwiZGF0Ijp7InAiOiIxNzIzMzI3OTMyIiwiciI6IkhOMTAiLCJjIjoiY3FjbG91ZCIsInUiOjE3MDA0NjI1MTk5fSwiaXNzIjoiaHR0cHM6Ly9sb2wucXEuY29tIiwicGx0Ijp7ImRldiI6InVua25vd24iLCJpZCI6InVua25vd24ifSwiZXhwIjoxNzI5NzY2MTE1LCJpYXQiOjE3Mjk3NjU1MTUsImp0aSI6Il9MTXR0Y29vY1JvIiwiY2lkIjoibG9sIn0.WPiGLEWgxX-n2O6pmZu1Sg_aNJ-LBuZ0OM0DhW1L-4iHKwn5BxljeeMpWWKH33_9aOu5MLXFDpWdeRKWt3eatthoT7ynNPBzKFMjsoVPxxZQXN5qfF04bc_f4ObTBOpK3oaLdkCG9RpEuiKup3LOQVk_yJEvd4OGUMavMbv0j8hVjFalcg7xKEZt8thHuhMJLC3EZ3E_YfzFD2LYjGpy5j9XOmHljx2sRdLle2IRIhD6Kdq50Yd2wKe6UEf1hLFO6I_5dUNewcqFI-PwMnouagd_fyByCSyPpQ9O4vIcv6NwntrHH-NxZDs1WUbNIzqcIi103zfYV7jHJBwjG1XpfQ', timestamp=1729766018.1689417)
2024-10-24 18:33:38,264 - [Crash] ERROR - SearchInterface(puuid(int)=0, gameLoadingTask(NoneType)=None, currentSummonerName(NoneType)=None, detailViewLoadTask(NoneType)=None, loadingGameId(int)=0)
2024-10-24 18:33:38,264 - [Crash] ERROR - GameInfoInterface(isAram(bool)=False, allyChampions(dict)={}, allyOrder(list)=[], queueId(int)=0)
2024-10-24 18:33:38,264 - [Crash] ERROR - CareerInterface(currentSummonerName(NoneType)=None, puuid(NoneType)=None, showTagLine(bool)=False, recentTeammatesInfo(NoneType)=None, rankInfo(list)=[['单 / 双排'], ['灵活排位']], recentTeammatesFlyout(NoneType)=None, games(list)=[], loadGamesTask(NoneType)=None)
2024-10-24 18:33:38,264 - [Crash] ERROR - AuxiliaryInterface()
2024-10-24 18:33:38,264 - [Crash] ERROR - SettingInterface()

```

### 您进行游戏的服务器（若有）

黑色玫瑰

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
解压缩了再开
