### ISSUE TITLE
[BUG] 更新后启动报错 ModuleNotFoundError: No module named 'PyQt5.QtCore'

### ISSUE THREAD

**Issue by helloAhao096** [Zzaphkiel/Seraphine#528]
### 问题描述

Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "app\view\main_window.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "qasync\__init__.py", line 80, in <module>
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'PyQt5.QtCore'

是少打包了这个Core么，我是通过你自带的自动更新来更新的程序

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by helloAhao096** [comment]
> 重新下个试试

准备把原来的删掉重试一下，但是原来的这个文件夹直接被程序占用了，无法删除，可能是qt的模块在后台进程中还有存在，能否在异常处理中再判断一下所有的进程，主程序不存活的话把开的所有进程都杀了

**Comment by Zzaphkiel** [comment]
没法处理删除时因为占用而不能删除的异常，因为主程序都不存在了，何谈判断主程序存不存活？重启电脑试试吧。
